import * as E from './lab-engine.js?v=workshop44';
export const courseNames={wired:'Home network → rack server → VMs',nas:'Rack storage & RAID',virtual:'Virtualization server',wifi:'Wireless home office',routed:'Two subnets, one router',cloud:'Local storage + cloud backup',trouble:'Repair a faulty network',free:'Build your own network'};
const d=(s,t,n=0)=>E.ofType(s,t)[n], link=(s,a,ap,b,bp,an=0)=>s.links.some(l=>!l.broken&&((l.a===d(s,a,an)?.id&&l.ap===ap&&l.b===(d(s,b)?.id||b)&&l.bp===bp)||(l.b===d(s,a,an)?.id&&l.bp===ap&&l.a===(d(s,b)?.id||b)&&l.ap===bp)));
export function buildCourse(mission,base){
 if(mission==='wired'||mission==='virtual')return base;
 const list=mission==='trouble'?[]:base.slice(0,mission==='cloud'?37:22);
 const add=(title,instruction,why,expect,pass,extra={})=>list.push({chapter:mission==='trouble'?0:3,title,instruction,why,expect,pass,...extra});
 const settings=(title,instruction,why,pass,type,section,field,extra={})=>add(title,instruction,why,'The live configuration matches the task.',pass,{settings:{type,section,field},action:'Open '+section.toLowerCase(),...extra});
 const place=(type,n=0)=>add('Add '+(n?'a second ':'')+E.catalog[type].name,'Press Add below. Keep open space around its connectors.','Each device has a specific job. The next steps explain its connections.','The new device is on the bench.',s=>!!d(s,type,n),{add:type,nth:n,action:'Add '+E.catalog[type].name});
 const connect=(a,ap,b,bp,cable,an=0)=>add(`Connect ${a}${an?' 2':''} ${ap.toUpperCase()} → ${b} ${bp.toUpperCase()}`,`Select the ${an?'second ':''}${a}. Drag ${ap.toUpperCase()} onto ${b} ${bp.toUpperCase()}. Or click the two empty socket markers.`,cable==='power'?'A power cord supplies energy. An Ethernet cord carries messages.':'Match both connector types. A cable alone does not configure an IP address.','A seated cable joins the two correct sockets.',s=>link(s,a,ap,b,bp,an),{a,ap,b,bp,aNth:an,cable,action:'Find the first socket'});
 const on=(type,n=0)=>add('Turn on '+type+(n?' 2':''),'Select the device and press Switch on in the workbench toolbar.','A device needs both a working power path and its power switch on.','The power light is on.',s=>!!d(s,type,n)&&E.powered(s,d(s,type,n).id),{powerType:type,nth:n,action:'Find the power button'});
 const test=(title,instruction,why,target='internet',protocol='https',extra={})=>add(title,instruction,why,'The requested test passes.',s=>s.walkthrough?.[extra.flag||'courseTest']===true&&E.test(s,d(s,'laptop')?.id,typeof target==='function'?target(s):target,protocol).ok,{runTest:{target,protocol,flag:extra.flag||'courseTest'},action:'Run this test',panel:'test',...extra});
 if(mission==='nas'){
 place('nas');add('Prepare to install NAS drives','Check the grounded mat, wrist strap and airflow boxes. Leave the NAS OFF and unplugged.','Static sparks can harm electronics. Fit internal parts before restoring power.','All safety checks are ready.',s=>s.safety.mat&&s.safety.strap&&s.safety.clearance&&!d(s,'nas')?.on&&!s.links.some(l=>l.type==='power'&&(l.a===d(s,'nas')?.id||l.b===d(s,'nas')?.id)),{safety:true});
 settings('Fit four 1 TB drives','Choose 1 TB SATA SSD in Install parts. Press Install part four times.','NAS means Network Attached Storage. Its disks hold files for network clients.',s=>d(s,'nas')?.disks.length===4&&d(s,'nas').disks.every(x=>x.tb===1),'nas','Install parts','partChoice',{choose:'disk|1'});
 settings('Support and mount the NAS at U7','Check compatible rails / shelf. Set Bottom rack unit to 7, then Mount in rack.','This NAS uses a supported 2U shelf at U7–U8. Keep air vents clear.',s=>d(s,'nas')?.rack===7,'nas','Rack placement','rackU',{choose:'7'});
 connect('nas','ac','pdu','out4','power');on('nas');settings('Initialize RAID 5','Choose RAID 5 and press Initialize RAID.','Four equal 1 TB disks provide about 3 TB before overhead. Distributed parity allows one failed disk.',s=>d(s,'nas')?.raid==='5'&&E.raidStatus(d(s,'nas')).ok,'nas','Storage & RAID','raidLevel',{choose:'5'});
 connect('nas','eth','switch','p3','cat5e');settings('Enable file sharing','Check SMB file service in the NAS Network configuration. Leave the NAS on DHCP.','SMB means Server Message Block. It provides file sharing, commonly over TCP 445.',s=>d(s,'nas')?.services.file,'nas','Network configuration','fileService');
 test('Read the NAS share','Open the laptop diagnostic tool and run this test. The laptop will request the NAS SMB service.','A healthy disk array still needs a powered network, IP settings and a running file service.',s=>d(s,'nas')?.id,'smb');
 settings('Fail one member drive','In the drive list, press Simulate failure next to drive 1. Leave the other three drives healthy.','RAID 5 survives one failed member. Degraded means accessible with less protection.',s=>E.raidStatus(d(s,'nas')).failed===1&&E.raidStatus(d(s,'nas')).ok,'nas','Storage & RAID','raidLevel');
 test('Read files while degraded','Run the SMB test again before rebuilding.','Parity and surviving blocks can supply the missing data. A second failed disk exceeds RAID 5 tolerance.',s=>d(s,'nas')?.id,'smb',{flag:'degradedTest'});
 settings('Replace and rebuild the drive','Press Replace & rebuild on the failed member. Wait for the completion message.','The new drive receives reconstructed data. Real rebuilds can take hours. RAID does not replace backups.',s=>E.raidStatus(d(s,'nas')).failed===0&&s.events.some(x=>x.includes('Rebuild completed')),'nas','Storage & RAID','raidLevel');
 }else if(mission==='wifi'){
 place('ap');connect('ap','eth','switch','p3','cat5e');on('ap');settings('Configure your wireless network','Use SSID HomeLab, password learnlab123, WPA2-AES, 5 GHz and channel 36. Press Apply Wi-Fi settings.','SSID is the network name. The password protects entry. The channel is a slice of radio spectrum. PoE supplies this AP over Ethernet.',s=>{const a=d(s,'ap');return a?.ssid==='HomeLab'&&a.password==='learnlab123'&&a.security==='WPA2-AES'&&a.band==='5'&&a.channel==='36'},'ap','Wireless settings','apSsid');
 settings('Join from the laptop','In laptop Settings → Wi-Fi, choose HomeLab and enter learnlab123. Press Connect; keep automatic addressing.','The laptop must first join the radio network, then request IP settings. Matching a name alone is not enough.',s=>!!d(s,'laptop')?.network.wifi&&E.wifiAssociation(s,d(s,'laptop').id).ok,'laptop','Network configuration','useWifi');
 add('Unplug the laptop Ethernet cord','Select the laptop ETH plug. Drag it away from the socket and release, or use Connected cables → Unplug. Leave its power cord connected.','Removing the wired path proves that your radio path works.','No Ethernet cable is connected to the laptop.',s=>!s.links.some(l=>l.type!=='power'&&(l.a===d(s,'laptop')?.id||l.b===d(s,'laptop')?.id)),{reveal:'cableList',action:'Open cable list'});
 test('Browse through Wi-Fi','Run this test from the wireless laptop.','Laptop radio → AP → switch → router → ONT → provider. The AP bridges; the router routes.');
 }else if(mission==='routed'){
 place('laptop',1);connect('laptop','ac','wall','out2','power',1);on('laptop',1);
 settings('Create the second router subnet','Enable Separate LAN2 subnet. Set its address to 192.168.60.1, keep mask 255.255.255.0, DHCP and routing on, then Apply router settings.','A router can have an address in each network. Hosts use the nearby address as their gateway.',s=>d(s,'router')?.router.secondary&&d(s,'router').router.second==='192.168.60.1','router','Router configuration','secondary');
 settings('Put switch P4 and P5 in VLAN 20','In Access-port VLANs, set P4 and P5 to 20. Keep P1 and P2 in VLAN 1. Apply the switch settings.','A VLAN is a separate local broadcast group. Do this BEFORE connecting LAN2 to avoid a bridge loop.',s=>d(s,'switch')?.ports.p4.vlan===20&&d(s,'switch').ports.p5.vlan===20&&d(s,'switch').ports.p1.vlan===1&&d(s,'switch').ports.p2.vlan===1,'switch','Access-port VLANs','vlan-p4');
 connect('laptop','eth','switch','p4','cat5e',1);connect('router','lan2','switch','p5','cat5e');settings('Check laptop 2 gets the second subnet','In the second laptop’s Settings, select automatic DHCP and Save. Look for 192.168.60.x and gateway 192.168.60.1.','The DHCP request stays in VLAN 20. The router supplies settings for its second interface.',s=>d(s,'laptop',1)&&E.network(s,d(s,'laptop',1).id).ok&&E.network(s,d(s,'laptop',1).id).gateway==='192.168.60.1','laptop','Network configuration','ipMode',{nth:1});
 test('Ping between the two subnets','Run the test from laptop 1 to laptop 2.','Frames reach the first gateway. The router forwards the packet onto the other subnet. The reply needs a route back.',s=>d(s,'laptop',1)?.id,'ping');
 }else if(mission==='cloud'){
 add('Choose a cloud responsibility model','In the cloud panel choose Hybrid and IaaS, then Provision learning account.','IaaS means Infrastructure as a Service: rented compute, storage and networking. You manage the guest OS and app. Hybrid joins distinct cloud environments; this lab simplifies that integration.','Hybrid and IaaS are selected and provisioned.',s=>s.cloud.account&&s.cloud.model==='hybrid'&&s.cloud.service==='iaas',{panel:'vm',action:'Open cloud workspace'});
 add('Select the server as backup source','In the laptop Cloud console, choose your server as Backup source. Press Run simulated off-site backup.','A separate recovery copy protects against events that RAID alone cannot fix. The source and cloud network path must work.','An off-site recovery copy is recorded from the server.',s=>s.cloud.backup&&s.cloud.sourceName===d(s,'server')?.name,{panel:'vm',action:'Prepare backup source',prepareBackup:true});
 add('Verify the recovery record','Press Verify recovery copy below the backup message.','A backup needs checking. This exercise verifies its simulated record; a real recovery plan also restores and tests files.','The recovery record reports verified.',s=>s.cloud.verified===true,{panel:'vm',action:'Open cloud workspace'});
 }else if(mission==='trouble'){
 add('Inspect the failed physical link','Open Connected cables. Find the damaged Ethernet cable to the laptop. Press Repair.','Start with power and the physical path before changing addresses.','The damaged cable is repaired.',s=>s.links.every(l=>!l.broken),{reveal:'cableList',action:'Open cable list'});
 settings('Restore DHCP','Select the router. Enable DHCP and press Apply router settings. Leave DNS alone for this step.','DHCP lends the IP address, mask, gateway and DNS setting. Without it, a Windows IPv4 client may self-assign APIPA.',s=>!!d(s,'router')?.router.dhcp,'router','Router configuration','dhcp');
 test('Test an IP address first','Run a ping test to the Internet endpoint.','An IP-based ping avoids DNS. Passing this check does not prove that named web pages work.','internet','ping',{flag:'ipTest'});
 settings('Fix the DNS resolver','Change router DNS from 192.168.50.250 to 192.168.50.1, then Apply router settings.','DNS means Domain Name System. It finds records for names. In this lab the router forwards DNS queries.',s=>d(s,'router')?.router.dns==='192.168.50.1','router','Router configuration','routerDns');
 test('Verify the complete web path','Run the HTTPS test. Read every stage of the result.','A good fix restores the intended service. Cable, address, routing, DNS, TCP and TLS checks must agree.');
 }else if(mission==='free'){
 add('Explore your computer desktop','Select your powered laptop and choose Open laptop. Open Learning repositories on the desktop.','Free build can still have a gentle starting checklist. Turn help to Free build whenever you want independent practice.','The desktop has opened at least once.',s=>s.desktopProgress?.opened===true,{desktop:true,action:'Open laptop desktop'});
 }
 return list;
}
export function courseChapters(mission){if(mission==='trouble')return ['Find → repair → verify'];if(mission==='wired'||mission==='virtual')return ['Your first power-up','Build the network','Open a web page','Build a rack server','Run a virtual machine'];return ['Your first power-up','Build the network','Open a web page',({nas:'Build and recover storage',wifi:'Connect over Wi-Fi',routed:'Route between subnets',cloud:'Build host & protect data',free:'Explore the desktop'})[mission]||'Practice'];}
