import * as E from './lab-engine.js?v=workshop44qa1';
import {modelSnapshot} from './lab-model3d-data.js?v=workshop44qa1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function setupModel3D(api){
 let opened=null,chosen=null,scene=null,token=0,fingerprint='',spec=null,previousFocus=null;
 const dialog=document.createElement('dialog');dialog.id='model3dDialog';dialog.className='model3d-dialog';dialog.setAttribute('aria-labelledby','model3dTitle');dialog.innerHTML=`<header class="model3d-heading"><div><p class="model3d-eyebrow">WIRING EXPLORER · REAL-TIME 3D</p><h2 id="model3dTitle">See how it fits.</h2></div><button type="button" data-m3-close aria-label="Close 3D and return to the lab">Back to lab <span aria-hidden="true">×</span></button></header><div class="model3d-layout"><section class="model3d-visual" aria-label="3D exploration"><div class="model3d-camera" role="group" aria-label="Camera views"><button data-m3-view="hero">Angled</button><button data-m3-view="front">Front</button><button data-m3-view="rear">Back</button><button data-m3-view="top">Top</button><button data-m3-focus>Focus socket</button><span></span><button data-m3-zoom="out" aria-label="Zoom 3D model out">−</button><button data-m3-zoom="in" aria-label="Zoom 3D model in">+</button></div><div id="model3dStage" class="model3d-stage"></div><p id="model3dLoad" class="model3d-load" role="status">Loading your 3D model…</p><div class="model3d-caption"><span>↔ Drag to rotate</span><span>⊕ Scroll or pinch to zoom</span><span>Click a socket to explore</span></div><div class="model3d-explode"><div><label for="model3dAmount">Pull the plugs apart</label><output id="model3dPercent">0%</output></div><input id="model3dAmount" type="range" min="0" max="100" value="0" aria-label="Connection explosion amount"><div class="model3d-animation"><button data-m3-animate="0">Fit together</button><button data-m3-animate="1" class="m3-primary">Explode connections ↗</button></div><p>Only the view moves. Your cables stay connected in the lab.</p></div></section><aside class="model3d-inspector"><label class="model3d-device-label">Equipment<select id="model3dDevice"></select></label><div class="model3d-steps"><span>1 Rotate the model</span><span>2 Pick a socket below</span><span>3 Explore its plug</span></div><h3>Choose a connection</h3><div id="model3dPorts" class="model3d-port-list" role="group" aria-label="Equipment sockets"></div><article id="model3dDetails" aria-live="polite"></article><button class="m3-primary model3d-connect" data-m3-connect>Wire this socket in the lab</button><p class="model3d-small">Return to the main 3D lab to drag cables, switch power on, or unplug a wire.</p></aside></div><footer class="model3d-footer"><span><i class="m3-green"></i> Green: power available</span><span><i class="m3-blue"></i> Blue: physical data link ready</span><p>Pulses show connection status, not measured traffic. Generic teaching models; shapes and spacing are simplified.</p></footer>`;document.body.append(dialog);
 const $=id=>dialog.querySelector('#'+id),ports=()=>spec?.ports||[];
 function details(id){chosen=id;const p=ports().find(p=>p.id===id);if(!p)return;for(const b of dialog.querySelectorAll('[data-m3-port]'))b.setAttribute('aria-pressed',String(b.dataset.m3Port===id));const status=p.connected?(p.live?(p.power?'POWER AVAILABLE':'PHYSICAL LINK READY'):'CONNECTED · NOT READY'):'EXAMPLE PLUG · NOT CONNECTED';$('model3dDetails').innerHTML=`<p class="model3d-state ${p.live?(p.power?'m3-power':'m3-data'):''}">${status}</p><h3>${esc(p.description.name)}</h3><p>${esc(p.description.fit)}</p><div class="model3d-route"><b>${esc(spec.name)} · ${esc(p.id.toUpperCase())}</b><span aria-hidden="true">↓</span><b>${p.connected?esc(p.peer+' · '+p.peerPort?.toUpperCase()):'No cable attached in your lab'}</b>${p.connected?`<small>${esc(E.cableTypes[p.cable]?.name)} · ${p.length} ft</small>`:'<small>The sample plug shows which shape fits this socket.</small>'}</div><p>${esc(p.description.job)}</p>${p.connected?`<p class="model3d-reason">${esc(p.why)}</p>`:''}`;scene?.select(id);}
 function fail(message){$('model3dLoad').hidden=false;$('model3dLoad').textContent=message+' The connection close-up below still works.';}
 async function mount(){const myToken=++token;scene?.dispose();scene=null;$('model3dStage').replaceChildren();$('model3dLoad').hidden=false;$('model3dLoad').textContent='Loading your 3D model…';try{const {createModelScene}=await import('./lab-model3d-scene.js?v=workshop44qa1');if(myToken!==token||!dialog.open)return;scene=createModelScene($('model3dStage'),spec,{onSelect:details,onError:fail,onExplode:amount=>{$('model3dAmount').value=String(Math.round(amount*100));$('model3dPercent').textContent=Math.round(amount*100)+'%';}});scene.select(chosen);$('model3dLoad').hidden=true;scene.animateTo(1);}catch(error){if(myToken!==token)return;console.error('3D equipment view:',error);fail('This browser could not start the 3D display.');}}
 function refresh(){if(!dialog.open||!opened)return;const next=modelSnapshot(api.getState(),opened);if(!next){dialog.close();return;}const signature=JSON.stringify(next);if(signature===fingerprint)return;fingerprint=signature;spec=next;$('model3dTitle').textContent=spec.name;$('model3dDevice').innerHTML=api.getState().devices.filter(d=>!d.virtual&&E.catalog[d.type]).map(d=>`<option value="${esc(d.id)}" ${d.id===opened?'selected':''}>${esc(d.name)}</option>`).join('');$('model3dPorts').innerHTML=ports().map((p,i)=>`<button data-m3-port="${p.id}" aria-pressed="false"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(p.id.toUpperCase())}</b><i class="${p.live?(p.power?'m3-green':'m3-blue'):'m3-idle'}" aria-label="${esc(p.why)}"></i></button>`).join('');chosen=ports().some(p=>p.id===chosen)?chosen:ports().find(p=>p.connected)?.id||ports()[0]?.id;details(chosen);mount();}
 function open(id,port){if(!E.find(api.getState(),id))return;previousFocus=document.activeElement;opened=id;chosen=port||null;fingerprint='';if(!dialog.open)dialog.showModal();dialog.scrollTop=0;refresh();}
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-m3-close'))dialog.close();if(b.dataset.m3Port)details(b.dataset.m3Port);if(b.dataset.m3View)scene?.view(b.dataset.m3View);if(b.hasAttribute('data-m3-focus'))scene?.focus();if(b.dataset.m3Zoom)scene?.zoom(b.dataset.m3Zoom==='in'?.83:1.2);if(b.dataset.m3Animate!==undefined)scene?.animateTo(Number(b.dataset.m3Animate));if(b.hasAttribute('data-m3-connect')){const id=opened,p=chosen;dialog.close();api.openConnection(id,p);}});
 $('model3dAmount').addEventListener('input',e=>scene?.setExplosion(Number(e.target.value)/100));$('model3dDevice').addEventListener('change',e=>{opened=e.target.value;chosen=null;fingerprint='';refresh();dialog.scrollTop=0});dialog.addEventListener('close',()=>{++token;scene?.dispose();scene=null;opened=null;fingerprint='';$('model3dStage').replaceChildren();previousFocus?.focus?.({preventScroll:true});});return {open,refresh};
}
