import {refreshConnectionPulses} from './lab-connection-pulses.js?v=laptop42';
import * as E from './lab-engine.js?v=laptop42';
import {portState} from './lab-hardware.js?v=laptop42';
import {templates,recommend,buildTemplate,toolsCatalog,freshness} from './lab-planner.js?v=laptop42';
import {commands,runPowerShell} from './lab-powershell.js?v=laptop42';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function setupStudio(api){
 const $=id=>document.getElementById(id),state=()=>api.getState(),scene=$('scene');let owner=state(),undo=null,plan=null,audio=null,zoom=1;
 let pref={sound:false,motion:!window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches,steps:true,volume:.18};try{const saved=JSON.parse(localStorage.getItem('home-lab-studio-prefs')||'{}');for(const k of ['sound','motion','steps'])if(typeof saved[k]==='boolean')pref[k]=saved[k];if(Number.isFinite(saved.volume))pref.volume=Math.max(0,Math.min(.4,saved.volume));}catch{}
 const save=()=>{try{localStorage.setItem('home-lab-studio-prefs',JSON.stringify(pref))}catch{}};
 const frame=document.createElement('div');frame.id='benchViewport';frame.className='bench-viewport';frame.setAttribute('tabindex','0');frame.setAttribute('role','region');frame.setAttribute('aria-label','Scrollable workbench and rack. Use arrow keys or scroll to explore.');scene.before(frame);frame.append(scene);
 const controls=document.createElement('div');controls.className='studio-bench-controls';controls.innerHTML='<div class="zoom-controls" aria-label="Workbench zoom"><button id="zoomOut" aria-label="Zoom out">−</button><output id="zoomValue">100%</output><button id="zoomIn" aria-label="Zoom in">+</button><button id="zoomFit">Fit width</button><button id="benchUp" aria-label="Scroll workbench up">↑ Up</button><button id="benchDown" aria-label="Scroll workbench down">↓ Down</button></div><div class="studio-actions"><button id="soundToggle" aria-pressed="false">Sound off</button><label class="volume-control">Volume<input id="effectVolume" type="range" min="0" max="40" step="2" aria-label="Effects volume"></label><button id="motionToggle" aria-pressed="true">Connection pulses on</button><button id="stepsToggle" aria-pressed="true">Guided steps on</button><a href="#labStudio">Planner &amp; PowerShell ↓</a></div><div class="connection-pulse-legend"><span><i class="power-status-key"></i>Green: power available</span><span><i class="data-status-key"></i>Blue: data link ready</span></div><p id="fxMeaning">Pulses run continuously while the connection is ready. These are status animations, not measured traffic or electrical waveforms. Run a test to check IP, DNS and services.</p>';frame.before(controls);
 function applyPrefs(){document.body.classList.toggle('lab-reduce-motion',!pref.motion);$('coach').hidden=!pref.steps;$('soundToggle').textContent=pref.sound?'Sound on':'Sound off';$('soundToggle').setAttribute('aria-pressed',String(pref.sound));$('effectVolume').value=String(Math.round(pref.volume*100));$('motionToggle').textContent=pref.motion?'Connection pulses on':'Connection pulses off';$('motionToggle').setAttribute('aria-pressed',String(pref.motion));$('stepsToggle').textContent=pref.steps?'Guided steps on':'Guided steps off';$('stepsToggle').setAttribute('aria-pressed',String(pref.steps));save();}
 async function sound(type){if(!pref.sound||pref.volume===0)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){$('fxMeaning').textContent='Sound is unavailable in this browser. Written results and visual indicators remain available.';return;}audio??=new Audio();if(audio.state==='suspended')await audio.resume();const pattern=type==='error'?[[220,0,.13],[165,.14,.2]]:type==='complete'?[[523,0,.12],[659,.12,.12],[784,.24,.24]]:[[659,0,.09],[880,.1,.13]];for(const [hz,offset,len]of pattern){const oscillator=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime+offset;oscillator.type='sine';oscillator.frequency.value=hz;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(pref.volume,t+.012);gain.gain.exponentialRampToValueAtTime(.001,t+len);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(t);oscillator.stop(t+len+.01);}}catch{$('fxMeaning').textContent='Sound could not start. Toggle Sound on after interacting with the page; all results remain visible.';}}
 $('soundToggle').onclick=()=>{pref.sound=!pref.sound;applyPrefs();if(pref.sound)sound('connect');};$('effectVolume').oninput=()=>{pref.volume=Number($('effectVolume').value)/100;save();};$('motionToggle').onclick=()=>{pref.motion=!pref.motion;applyPrefs();refreshScene();};$('stepsToggle').onclick=()=>{pref.steps=!pref.steps;if(!pref.steps)api.stopVoice?.();applyPrefs();};applyPrefs();
 function applyZoom(value){zoom=Math.min(1.8,Math.max(.35,value));scene.style.width=Math.max(1000,frame.clientWidth||1000)+'px';scene.style.zoom=String(zoom);$('zoomValue').textContent=Math.round(zoom*100)+'%';$('zoomOut').disabled=zoom<=.35;$('zoomIn').disabled=zoom>=1.8;api.renderScene();}
 $('zoomOut').onclick=()=>applyZoom(zoom-.15);$('zoomIn').onclick=()=>applyZoom(zoom+.15);$('zoomFit').onclick=()=>applyZoom((frame.clientWidth||800)/Math.max(1000,frame.clientWidth||1000));$('benchUp').onclick=()=>frame.scrollBy({top:-Math.max(220,(frame.clientHeight||520)*.7),behavior:pref.motion?'smooth':'instant'});$('benchDown').onclick=()=>frame.scrollBy({top:Math.max(220,(frame.clientHeight||520)*.7),behavior:pref.motion?'smooth':'instant'});
 window.addEventListener('resize',()=>applyZoom(zoom));applyZoom(1);
 // Expanding the bench changes its container without a window resize.
 let frameWidth=frame.clientWidth;const resizeObserver=typeof window.ResizeObserver==='function'?new window.ResizeObserver(()=>{if(frame.clientWidth!==frameWidth){frameWidth=frame.clientWidth;applyZoom(zoom);}}):null;resizeObserver?.observe(frame);
 function refreshScene(){if(typeof refreshConnectionPulses==='function')refreshConnectionPulses($('wires'),state(),portState);}
 function onResult(r){sound(r.ok?'connect':'error');refreshScene();}
 // True tabs with keyboard navigation and preserved form state.
 const tabs=[...document.querySelectorAll('[data-studio-tab]')];function showTab(name){for(const b of tabs){const selected=b.dataset.studioTab===name;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;$('panel'+b.dataset.studioTab).hidden=!selected;}}
 for(const b of tabs){b.onclick=()=>showTab(b.dataset.studioTab);b.onkeydown=e=>{const i=tabs.indexOf(b);let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();showTab(tabs[n].dataset.studioTab);tabs[n].focus();}};}
 $('templateChoices').innerHTML=Object.entries(templates).map(([id,t],i)=>`<button data-template="${id}"><span>0${i+1}</span><b>${esc(t.title)}</b><small>${esc(t.subtitle)}</small></button>`).join('');
 function analyze(){plan=recommend($('planGoal').value,$('planType').value,Number($('planRAM').value),Number($('planCPU').value),Number($('planDrives').value),$('planPriority').value,$('planOwned').value);if(!plan.ok){$('planResult').innerHTML='<h3>Let’s narrow the setup</h3><p>'+esc(plan.why)+'</p>';sound('error');return;}
 const {t,id}=plan;$('planResult').innerHTML=`<p class="eyebrow">${plan.recognized?'MATCHED STARTING POINT':'SELECTED STARTING POINT'}</p><h3>${esc(t.title)}</h3><p>${esc(t.subtitle)}</p>${plan.owned?`<p><b>Your parts note:</b> ${esc(plan.owned)}</p>`:''}<h4>Core equipment</h4><div class="plan-parts">${t.devices.map(x=>`<span>${esc(E.catalog[x].name)}</span>`).join('')}</div><h4>Resource checks &amp; priorities</h4><ul>${plan.notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Build in this order</h4><ol class="plan-steps">${t.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h4>Tradeoffs to understand</h4><ul>${t.tradeoffs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><button id="loadTemplate" class="primary">Load working example</button><button id="downloadPlan">Download these instructions</button><p class="studio-note">Loading replaces the current bench; Undo template load brings it back. The example uses fixed lab parts, not the hardware quantities you entered.</p>`;
 $('loadTemplate').onclick=()=>{try{const next=buildTemplate(id);const previous=JSON.parse(JSON.stringify(state()));api.replace(next);owner=state();undo=previous;$('undoTemplate').hidden=false;$('templateStatus').textContent=t.title+' loaded. Inspect its cables and follow the plan. Undo is available until you load another lab.';sound('complete');}catch(e){$('templateStatus').textContent='Template could not load: '+e.message;sound('error');}};
 $('downloadPlan').onclick=()=>{const body=[t.title,t.subtitle,'Your goal: '+$('planGoal').value,'Parts note: '+$('planOwned').value,'Resource checks:',...plan.notes,'Build steps:',...t.steps.map((x,i)=>(i+1)+'. '+x),'Tradeoffs:',...t.tradeoffs,'Teaching plan only; measure and validate your real hardware and provider.'].join('\n\n');const url=URL.createObjectURL(new Blob([body],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download='home-lab-'+id+'-plan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 }
 $('planAnalyze').onclick=analyze;for(const b of document.querySelectorAll('[data-template]'))b.onclick=()=>{$('planType').value=b.dataset.template;$('planGoal').value=templates[b.dataset.template].subtitle;analyze();};$('undoTemplate').onclick=()=>{if(!undo)return;const prior=undo;undo=null;api.replace(prior);owner=state();$('undoTemplate').hidden=true;$('templateStatus').textContent='Your previous build was restored.';sound('connect');};
 function fill(id,items){const cur=$(id).value;$(id).innerHTML=items.map(([v,t])=>`<option value="${esc(v)}" ${cur===v?'selected':''}>${esc(t)}</option>`).join('');}
 const equipmentNotes={laptop:'Client with a simulated Windows desktop, IP settings and Wi-Fi radio.',router:'Routes between IP networks; includes DHCP, NAT and two LAN interfaces.',switch:'Eight 1 Gb/s copper ports plus one SFP+ slot; access VLANs and simplified PoE.',server:'AM4 / DDR4 teaching host: CPU, RAM, NIC, four drive bays, RAID and VMs.',nas:'Four-bay network storage with RAID and SMB sharing.',ap:'2.4/5 GHz radio, SSID, WPA2/WPA3 and an Ethernet uplink.',ups:'900 W teaching limit; short power-loss exercise, no runtime estimate.',pdu:'Eight power outputs; distribution only, no battery.',surge:'Six outputs; direct wall connection, no battery.',ont:'Provider SC fiber handoff to Ethernet WAN.',panel:'Four passive front-to-back patch pairs. Does not route or switch packets.'};
 function components(){const q=$('componentSearch').value.trim().toLowerCase();const list=Object.entries(equipmentNotes).filter(([id,text])=>(id+' '+E.catalog[id].name+' '+text).toLowerCase().includes(q));const partList=[['32 GB DDR4 UDIMM','AM4 board memory. DDR5 and laptop SODIMM are incompatible.','ram','32'],['8-core AM4 CPU','Socket must match. Fit cooler and thermal paste before boot.','cpu','AM4-8'],['10 Gb/s SFP+ NIC','Needs a matching switch slot and SR optics + LC fiber, or DAC. Copper ports remain 1 Gb/s.','nic','10g'],['1 TB SATA SSD','Install four equal members to practice RAID 10 or RAID 5.','disk','1']].filter(p=>p.slice(0,3).join(' ').toLowerCase().includes(q));$('componentResults').innerHTML=list.map(([id,text])=>`<article><h4>${esc(E.catalog[id].name)}</h4><p>${esc(text)}</p><button data-add="${id}">Add to bench</button></article>`).join('')+partList.map(([name,text,part,value])=>`<article><h4>${esc(name)}</h4><p>${esc(text)}</p><button data-fit-studio="${part}|${value}">Fit in selected server</button></article>`).join('')||'<p>No matching component. Try power, router, RAM, storage or fiber.</p>';}
 $('componentSearch').oninput=components;components();document.addEventListener('click',e=>{const b=e.target.closest('[data-fit-studio]');if(!b)return;const d=E.find(state(),state().selected);if(!d||d.type!=='server')return api.result({ok:false,message:'Select a server on the workbench first. Shut it down, unplug it and prepare ESD tools before fitting parts.'});const [part,value]=b.dataset.fitStudio.split('|');api.result(E.fitPart(state(),d.id,part,value));});
 $('studioTool').innerHTML=toolsCatalog.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');function toolMeaning(){const t=toolsCatalog.find(t=>t.id===$('studioTool').value);$('toolMeaning').textContent=t.detail;$('toolCable').disabled=t.id!=='cable';$('toolDevice').disabled=['cable','power'].includes(t.id);}$('studioTool').onchange=toolMeaning;toolMeaning();
 $('toolRun').onclick=()=>{const s=state(),id=$('toolDevice').value,kind=$('studioTool').value;let ok=true,text='';if(kind==='cable'){const l=s.links.find(l=>l.id===$('toolCable').value);if(!l){ok=false;text='Connect a cable first.';}else{const link=portState(s,l.a,l.ap);ok=link.live;text=`${E.cableTypes[l.type].name} · ${l.length} ft\n${E.find(s,l.a).name} ${l.ap} ↔ ${E.find(s,l.b).name} ${l.bp}\nDamage: ${l.broken?'detected':'none modeled'}\n${link.why}\n${l.type==='power'?'Power cable: never carries network data.':'Physical link only. IP, DNS and service checks come next.'}`;}}else if(kind==='power'){const rows=s.devices.filter(d=>d.on&&!['wall','isp','panel'].includes(d.type));text='Nameplate planning sum, not a meter reading:\n'+rows.map(d=>`${d.name}: ${E.catalog[d.type].watts} W`).join('\n')+`\nTotal requested device load: ${rows.reduce((n,d)=>n+E.catalog[d.type].watts,0)} W\nA UPS limit is checked on its own downstream chain. Do not use this sum as a runtime estimate.`;}else if(kind==='raid'){const ds=s.devices.filter(d=>['server','nas'].includes(d.type));ok=ds.length>0&&ds.every(d=>E.raidStatus(d).ok);text=ds.length?ds.map(d=>`${d.name}: RAID ${d.raid||'unset'} · ${E.raidStatus(d).usable} TB\n${E.raidStatus(d).message}`).join('\n'):'Add a server or NAS first.';}else{const r=kind==='dns'?E.lookupDNS(s,id):E.test(s,id,'internet',kind);ok=r.ok;text=r.why+'\n'+(r.trace||[]).join('\n');api.test(r);} $('toolOutput').textContent=(ok?'PASS · ':'CHECK · ')+text;sound(ok?'connect':'error');};
 $('psCommandCards').innerHTML=commands.map((c,i)=>`<button data-ps-command="${i}">${esc(c.name)}</button>`).join('');function pickCommand(i){const c=commands[i];$('psInput').value=c.command;$('psMeaning').innerHTML=`<p>${esc(c.meaning)}</p><a href="${c.source}" target="_blank" rel="noopener">Microsoft command reference ↗</a>`;}pickCommand(0);for(const b of document.querySelectorAll('[data-ps-command]'))b.onclick=()=>pickCommand(Number(b.dataset.psCommand));
 $('psRun').onclick=()=>{const r=runPowerShell(state(),$('psDevice').value,$('psInput').value);if(r.changed)api.result({ok:r.ok,message:r.output});else sound(r.ok?'connect':'error');$('psOutput').textContent='PS (simulated)> '+$('psInput').value+'\n\n'+r.output;};$('psClear').onclick=()=>{$('psOutput').textContent='Output cleared. Choose a command and run it.';};$('psDevice').onchange=()=>{$('psOutput').textContent='Device changed. Run a command to inspect this device.';};
 function checkFresh(){for(const [id,out]of [['freshAge','freshAgeLabel'],['freshSilence','freshSilenceLabel'],['freshLag','freshLagLabel']])$(out).textContent=$(id).value+' ms';const r=freshness({eventAge:Number($('freshAge').value),arrivalGap:Number($('freshSilence').value),lag:Number($('freshLag').value),maxAge:Number($('freshMaxAge').value),maxSilence:Number($('freshMaxSilence').value),maxLag:Number($('freshMaxLag').value),connected:$('freshConnected').checked,gap:$('freshGap').checked,clockError:$('freshClock').checked});$('freshResult').className='fresh-result '+(r.ok?'ok':'error');$('freshResult').innerHTML=`<h4>${r.ok?'ACCEPT · within your practice policy':'BLOCK · do not treat this sample as current'}</h4><ul>${r.reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;return r;}
 for(const id of ['freshAge','freshSilence','freshLag','freshMaxAge','freshMaxSilence','freshMaxLag','freshConnected','freshGap','freshClock'])$(id).oninput=checkFresh;
 $('freshHealthy').onclick=()=>{$('freshAge').value='100';$('freshSilence').value='100';$('freshLag').value='50';$('freshConnected').checked=true;$('freshGap').checked=false;$('freshClock').checked=false;const r=checkFresh();sound(r.ok?'connect':'error');};$('freshStale').onclick=()=>{$('freshAge').value='5000';checkFresh();sound('error');};$('freshDrop').onclick=()=>{$('freshConnected').checked=false;checkFresh();sound('error');};checkFresh();
 function refresh(){if(owner!==state()){owner=state();undo=null;$('undoTemplate').hidden=true;$('templateStatus').textContent='';$('psOutput').textContent='Build changed. Run a command for the current device.';$('toolOutput').textContent='Build changed. Run the tool again.';}const devices=state().devices.filter(d=>['laptop','server','nas'].includes(d.type));fill('psDevice',devices.filter(d=>d.type!=='nas').map(d=>[d.id,d.name]));fill('toolDevice',devices.map(d=>[d.id,d.name]));fill('toolCable',state().links.map(l=>[l.id,E.find(state(),l.a).name+' '+l.ap+' ↔ '+E.find(state(),l.b).name+' '+l.bp]));refreshScene();}
 refresh();window.addEventListener('pagehide',()=>{resizeObserver?.disconnect();audio?.close?.();});return {refresh,refreshScene,onResult,sound};
}
