import * as E from './lab-engine.js?v=laptop42';
import {portState} from './lab-hardware.js?v=laptop42';
import {mountWithSupport,rackCheck,unmountToBench} from './lab-direct-actions.js?v=laptop42';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function rackGeometry(width,view){return {left:width-(view==='rack'?455:305),top:view==='rack'?150:315,width:view==='rack'?430:280,unit:44,header:95};}
export function rackPosition(d,width,height,view){const g=rackGeometry(width,view);return [(g.left+g.width/2)/width*100,(g.top+g.header+(E.RACK_UNITS-d.rack+1-E.catalog[d.type].u/2)*g.unit)/height*100];}
export function renderNetworkRack(s,width=1000){const g=rackGeometry(width,s.view),mounted=s.devices.filter(d=>d.rack!=null&&!['wall','isp'].includes(d.type)),used=mounted.reduce((n,d)=>n+E.catalog[d.type].u,0);
 return `<section class="network-rack" style="left:${g.left}px;top:${g.top}px;width:${g.width}px" aria-label="Network rack"><header><div><b>NETWORK RACK</b><span>${used} / 18U used · 1U = 1.75 in</span></div><button type="button" data-rack-view>View rack</button></header><p class="rack-instruction">Drag equipment onto a U number. Fit its rails or shelf first.</p><div class="rack-slots" style="height:${E.RACK_UNITS*g.unit}px">${Array.from({length:E.RACK_UNITS},(_,i)=>`<button type="button" class="rack-drop-slot" style="top:${i*g.unit}px;height:${g.unit}px" data-rack-u="${E.RACK_UNITS-i}" aria-label="Mount selected equipment at U${E.RACK_UNITS-i}"><b>U${E.RACK_UNITS-i}</b><span>Drop here</span><i></i></button>`).join('')}${mounted.map(d=>{const c=E.catalog[d.type],on=E.powered(s,d.id);return `<article class="rack-installed device ${s.selected===d.id?'selected':''}" data-device="${d.id}" style="top:${(E.RACK_UNITS+1-d.rack-c.u)*g.unit}px;height:${c.u*g.unit-3}px" aria-label="${esc(d.name)} mounted at U${d.rack}"><button class="rack-grip" type="button" data-device="${d.id}" aria-label="Inspect ${esc(d.name)}" title="Drag to move; double-click for connections"><i class="rack-power-light ${on?'on':''}"></i><b>${esc(d.name)}</b><span>U${d.rack}${c.u>1?'–'+(d.rack+c.u-1):''} · ⠿</span></button><div class="rack-port-bank">${Object.entries(c.ports).map(([p,k])=>{const st=portState(s,d.id,p);return `<button type="button" class="bench-socket rack-socket ${k} ${st.plugged?'occupied':''} ${st.live?'socket-live':''}" data-bench-device="${d.id}" data-bench-port="${p}" data-scene-port="${d.id}:${p}" aria-label="${esc(d.name+' '+p.toUpperCase()+': '+st.why)}"><span class="bench-socket-label">${esc(p.toUpperCase())}</span>${st.plugged?`<span class="bench-seated-plug ${st.link.type}" aria-hidden="true"></span>`:''}<span class="bench-link-led" aria-hidden="true"></span></button>`;}).join('')}</div></article>`;}).join('')}</div><footer>Drop at the <b>bottom U</b> the device will occupy. A 2U server at U4 fills U4 + U5. Heavy UPS units stay low.</footer></section>`;
}
export function setupRackActions(api){const s=()=>api.getState(),scene=document.getElementById('scene');const tools=document.createElement('div');tools.className='rack-tools';tools.innerHTML='<label><input type="checkbox" id="rackFitSupport"> Fit compatible rails / shelf when I mount</label><button id="rackToBench" type="button">Return selected to bench</button><span id="rackStatus" role="status">Drag rack equipment onto a numbered space. Click a space to mount the selected device.</span>';document.getElementById('benchViewport').before(tools);
 const status=document.getElementById('rackStatus');function attempt(id,u){const r=mountWithSupport(s(),id,u,document.getElementById('rackFitSupport').checked);status.textContent=r.message;status.classList.toggle('rack-error',!r.ok);api.result(r);return r;}
 scene.addEventListener('click',e=>{const b=e.target.closest('[data-rack-u],[data-rack-view]');if(!b)return;if(b.hasAttribute('data-rack-view')){s().view='rack';api.renderScene();return;}attempt(s().selected,Number(b.dataset.rackU));});
 document.getElementById('rackToBench').onclick=()=>{const r=unmountToBench(s(),s().selected);status.textContent=r.message;api.result(r);};
 function hover(id,x,y,type){scene.querySelectorAll('.rack-can-drop,.rack-cannot-drop').forEach(n=>n.classList.remove('rack-can-drop','rack-cannot-drop'));const target=document.elementFromPoint?.(x,y)?.closest('[data-rack-u],.rack-installed,.network-rack');if(!target)return null;let u=Number(target.dataset.rackU);if(!u){const d=E.find(s(),target.dataset.device);u=d?.rack;}if(!u)return {u:0,ok:false,message:'Drop onto a numbered U space.'};let trial=s(),candidate=id;if(!candidate&&type){trial={...s(),devices:[...s().devices]};const added=E.addDevice(trial,type);candidate=added.id;}if(!candidate)return {u,ok:false};const d=E.find(trial,candidate),shadow={...trial,devices:trial.devices.map(v=>v.id===candidate?{...v,rails:v.rails||document.getElementById('rackFitSupport').checked}:v)};const r=rackCheck(shadow,candidate,u);target.classList.add(r.ok?'rack-can-drop':'rack-cannot-drop');return {u,ok:r.ok,message:r.message};}
 function clear(){scene.querySelectorAll('.rack-can-drop,.rack-cannot-drop').forEach(n=>n.classList.remove('rack-can-drop','rack-cannot-drop'));}
 function refresh(){const d=E.find(s(),s().selected);document.getElementById('rackToBench').disabled=d?.rack==null;tools.hidden=!['bench','rear','rack'].includes(s().view);}
 refresh();return {attempt,hover,clear,refresh};}
