import * as E from './lab-engine.js?v=direct32';
export const templates={
 home:{title:'Connected home office',mission:'wifi',subtitle:'Ethernet + Wi-Fi, DHCP and one shared Internet path',devices:['ont','router','switch','laptop','ap','ups','pdu'],ram:0,steps:['Place an ONT, router, switch, laptop, access point, UPS and PDU. Power path: wall → UPS → PDU → individual devices.','Connect provider SC fiber → ONT; ONT Ethernet → router WAN; router LAN1 → switch P1; laptop → P2; AP → P3.','Enable router DHCP on 192.168.50.0/24. Use pool 100–150 and DNS 192.168.50.1.','Turn equipment on. Set the AP to HomeLab / learnlab123 with WPA2-AES or WPA3. Select Wi-Fi and matching credentials on the laptop to practice wireless access.','Run the IP & Wi-Fi checks. Then remove AP power or change its passphrase and explain where the path stops.'],tradeoffs:['Wired Ethernet avoids the shared radio medium for a fixed desk.','The router, ISP connection and switch remain single points of failure. A UPS only helps for a limited power outage.']},
 storage:{title:'Shared files & recovery',mission:'nas',subtitle:'Four-bay NAS, RAID 5, SMB and recovery practice',devices:['ont','router','switch','laptop','nas','ups','pdu'],ram:0,steps:['Build the wired home network and power it through a UPS and PDU.','Prepare ESD protection. With the NAS off and unplugged, install four equal 1 TB drives.','Fit supports and mount the NAS at U7. Connect its power and Ethernet to switch P3, then turn it on.','Initialize RAID 5 and enable SMB sharing. Four 1 TB drives yield about 3 TB before filesystem overhead.','Test laptop → NAS with SMB (TCP 445). Fail one disk, observe degraded access, replace and rebuild.','Keep a separate offline/off-site backup and test restoring it. RAID does not recover a deleted file or replace a backup.'],tradeoffs:['RAID 5 tolerates one member failure. A second failure before recovery loses the modeled array.','1 Gb/s links cap theoretical wire throughput at 125 MB/s before overhead. Faster drives cannot bypass that network limit.']},
 vm:{title:'Self-hosted VM cloud lab',mission:'virtual',subtitle:'One hypervisor, two isolated roles and a web service',devices:['ont','router','switch','laptop','server','ups','pdu'],ram:32,steps:['Build and test the wired network first. Keep management on the private LAN.','With the server unplugged, fit the AM4 CPU, cooler, DDR4 RAM, NIC and four equal SSDs. Enable ESD protection first.','Mount UPS low at U1 and server on supports at U4. Connect power and server Ethernet to switch P3.','Initialize RAID 10. Install the hypervisor, load drivers and enable firmware virtualization.','Create a web VM with 4 GB RAM / 2 vCPUs / 40 GB disk. Install and start the guest OS; enable its HTTPS service. Use an External virtual switch to reach the physical LAN.','Create a separate private test VM. Compare External, Internal and Private switch reachability. Internal/private mode alone supplies no NAT or DHCP service in this model.','Test from the laptop, export the lab, and practice restoring after a guest or host failure. A single host is not high availability.'],tradeoffs:['A group of VMs is virtualization. A private cloud also needs self-service, pooling, automation and operational controls.','Allocate for the actual workload and leave host headroom. Snapshots/checkpoints are not independent backups.']},
 trading:{title:'Trading-app staging lab',mission:'virtual',subtitle:'App + feed validation, latency budgets and stale-data drills',devices:['ont','router','switch','laptop','server','ups','pdu'],ram:32,steps:['Start with the self-hosted VM template. Use the home lab for development, replay and paper testing. Do not send real orders from this simulator.','Use wired Ethernet for host and client. Put the app and its feed consumer near each other. Measure the complete path to your actual data provider before choosing hosting.','Create App-Lab (4 GB / 2 vCPU / 40 GB) and Feed-Lab (4 GB / 2 vCPU / 40 GB). Both fit this 32 GB, eight-core teaching host. Separate services and credentials in a real deployment.','Track source event time, local arrival time, sequence gaps (when offered), stream health and processing backlog. Use a synchronized clock for time comparisons.','Set a freshness policy for each feed and strategy. Reject stale, gapped, disconnected or uncertain data; never silently reuse an old quote as current.','Use the freshness sandbox below to inject lag, clock error and feed loss. A healthy socket and a successful ping do not prove fresh market data.','Compare a home host with a cloud location near the provider using measured p50/p95/p99 latency and jitter. Test restore and failover. Keep backups and an independent recovery plan.'],tradeoffs:['No home-lab hardware can guarantee zero latency, zero stale data or uninterrupted service.','Cloud proximity can reduce a measured WAN path, but “cloud” alone does not guarantee low latency. A second VM on the same host does not protect against host failure.','A quiet market may produce no new event even while the stream is healthy. Interpret event age alongside heartbeat/subscription state and provider rules.']}
};
export function recommend(goal,choice,ram,cpu,drives,priority,owned=''){
 const text=(goal+' '+owned).toLowerCase();let id=choice;
 if(id==='auto')id=/trad|market|latency|quote|stale|stock/.test(text)?'trading':/nas|raid|file|backup|storage/.test(text)?'storage':/vm|virtual|cloud|host|app|docker/.test(text)?'vm':/wi.?fi|network|office|router|internet/.test(text)?'home':null;
 if(!id||!templates[id])return {ok:false,why:'Choose the closest template, or describe a home network, shared files, virtual machines, or a trading-app lab. This planner matches supported patterns; it is not an unrestricted AI designer.'};
 if(!Number.isInteger(ram)||ram<4||ram>256||!Number.isInteger(cpu)||cpu<1||cpu>64||!Number.isInteger(drives)||drives<0||drives>16)return {ok:false,why:'Use whole numbers: RAM 4–256 GB, CPU 1–64 cores and 0–16 drives.'};
 const t=templates[id],notes=[],vmLab=['vm','trading'].includes(id),guestRam=Math.max(0,ram-4),guestCPU=cpu,requiredRam=id==='trading'?8:id==='vm'?8:0;
 if(vmLab){notes.push(guestRam>=requiredRam?`${guestRam} GB remains after a 4 GB teaching host reserve; the two sample guests need 8 GB total.`:`RAM gap: the sample guests need 8 GB plus a 4 GB host reserve. Reduce guest size/count or add RAM.`);notes.push(cpu>=4?'The two 2-vCPU sample guests fit the entered core count without CPU overcommit.':'CPU gap: two 2-vCPU guests exceed the no-overcommit teaching budget. Start with one guest or use more cores.');}
 if(['storage','vm','trading'].includes(id))notes.push(drives>=4?'Four equal-capacity members meet the chosen classic RAID layout. Reserve additional space for snapshots and backups.':'Drive gap: the shown array uses four equal-capacity members. You can practice a two-disk RAID 1 design, but do not label it RAID 10 or four-disk RAID 5.');
 if(/ddr5|lga|xeon|ecc/.test(owned.toLowerCase()))notes.push('Compatibility check: this simulated server uses AM4 + DDR4 UDIMM. DDR5/LGA/Xeon parts cannot be substituted. Check motherboard CPU, memory and ECC support for real hardware.');
 if(priority==='uptime')notes.push('Prioritize a UPS, tested backups and independent recovery. Real failover requires another failure domain plus tested orchestration; one host stays a single point of failure.');
 if(priority==='speed')notes.push('Measure the bottleneck first. The lab has 1 Gb/s copper ports and a 10 Gb/s SFP+ server/switch option. A faster LAN cannot shorten an external provider path or fix stale data.');
 if(priority==='simple')notes.push('Start with one working wired client and one service. Prove power → IP → DNS → application before adding guests or a second subnet.');
 if(id==='trading')notes.push('Use the lab for safe staging/replay. Choose a live hosting location only after testing your provider, feed entitlement, burst load, jitter and recovery needs. No venue, price or performance guarantee is implied.');
 return {ok:true,id,t,notes,guestRam,guestCPU,recognized:choice==='auto',owned};
}
export function buildTemplate(id){if(!templates[id])throw Error('Unknown template');const s=E.fresh(templates[id].mission);s.safety={mat:true,strap:true,clearance:true};const d={};const must=r=>{if(!r.ok)throw Error(r.message||r.why);return r;};for(const type of templates[id].devices)d[type]=E.find(s,must(E.addDevice(s,type)).id);
 const cable=(a,p,b,q,t='cat5e')=>must(E.connect(s,a.id||a,p,b.id||b,q,t,6));
 cable('wall','out1',d.ups,'ac','power');cable(d.ups,'out1',d.pdu,'ac','power');d.ups.rails=true;must(E.mount(s,d.ups.id,1));
 const h=d.server||d.nas;if(h){if(d.server){for(const [part,value]of [['cpu','AM4-8'],['ram','32'],['cooler','yes'],['nic','1g']])must(E.fitPart(s,h.id,part,value));}for(let i=0;i<4;i++)must(E.fitPart(s,h.id,'disk','1'));h.rails=true;must(E.mount(s,h.id,d.server?4:7));}
 let outlet=1;for(const type of ['ont','router','switch','laptop',...(h?[h.type]:[])])cable(d.pdu,'out'+outlet++,d[type],'ac','power');
 cable('isp','fiber',d.ont,'fiber','sc');cable(d.ont,'lan',d.router,'wan');cable(d.router,'lan1',d.switch,'p1');cable(d.laptop,'eth',d.switch,'p2');if(h)cable(h,'eth',d.switch,'p3');if(d.ap)cable(d.ap,'eth',d.switch,'p3');
 for(const x of Object.values(d))x.on=true;d.router.router.dhcp=true;
 if(h){must(E.configureRaid(s,h.id,d.server?'10':'5'));if(d.server){h.os='Hypervisor';h.drivers=true;h.virt=true;for(const name of id==='trading'?['App-Lab','Feed-Lab']:['Web-Lab','Private-Lab']){const v=must(E.createVM(s,h.id,name,4,2,40,name==='Private-Lab'?'private':'external'));const guest=s.vms.at(-1);must(E.vmAction(s,guest.id,'install'));must(E.vmAction(s,guest.id,'start'));must(E.vmAction(s,guest.id,'service'));}}else h.services.file=true;}
 s.selected=d.laptop.id;s.events=['Loaded a working '+templates[id].title+' template. Inspect each connection, then practice the steps.'];return s;
}
export const toolsCatalog=[
 {id:'cable',name:'Cable tester',tag:'Physical layer',detail:'Checks the selected modeled cable for a broken conductor, seated ends and endpoint link. A basic wire-map tester does not certify bandwidth; a cable certifier performs additional measurements.'},
 {id:'power',name:'Power budget meter',tag:'Power',detail:'Adds nameplate teaching loads for powered-on devices. This is a planning sum, not measured watts or UPS runtime. Real sizing also considers VA, power factor, PoE budget and startup demand.'},
 {id:'ping',name:'ICMP reachability test',tag:'Networking',detail:'Asks a modeled public IP to reply. This checks the routed path. It does not test DNS, TCP ports, TLS or feed freshness.'},
 {id:'dns',name:'DNS lookup',tag:'Networking',detail:'Asks the configured name directory for the modeled example.com address. A correct lookup does not prove the web application is healthy.'},
 {id:'https',name:'HTTPS path test',tag:'Application',detail:'Follows IP, gateway, NAT, DNS, TCP 443 and TLS checks in the teaching engine.'},
 {id:'raid',name:'RAID health inspector',tag:'Storage',detail:'Reads array type, usable capacity and failed members. It makes the difference between degraded and unavailable storage visible.'}
];
export function freshness({eventAge,arrivalGap,lag,clockError,gap,connected,maxAge,maxSilence,maxLag}){const invalid=[eventAge,arrivalGap,lag,maxAge,maxSilence,maxLag].some(x=>!Number.isFinite(x)||x<0);if(invalid)return {ok:false,reasons:['Enter nonnegative finite ages and thresholds.']};const reasons=[];if(!connected)reasons.push('Feed disconnected');if(clockError)reasons.push('Clock synchronization uncertain');if(gap)reasons.push('Sequence gap or unverified recovery');if(eventAge>maxAge)reasons.push('Event age exceeds your policy');if(arrivalGap>maxSilence)reasons.push('No arrival within your silence policy');if(lag>maxLag)reasons.push('Processing backlog exceeds your policy');return {ok:!reasons.length,reasons:reasons.length?reasons:['All configured teaching checks pass. This is not a guarantee of market-data accuracy.']};}
