// Interaction layer: pointer movement never rebuilds the scene during a drag.
export function clampPoint(x,y){return [Math.max(13,Math.min(87,x)),Math.max(25,Math.min(89,y))];}
export function setupLabUX(api){
 const $=id=>document.getElementById(id),scene=$('scene');let drag=null,raf=0,suppressUntil=0,activeSection='Ports & cables',inspected=null,utterance=null,voiceToken=0,spokenStep='',voiceState='idle',voices=[],lastReturn=null;
 const state=()=>api.getState(),supported=!!window.speechSynthesis&&typeof window.SpeechSynthesisUtterance==='function';
 const paths={play:'M9 5l11 7-11 7z',pause:'M8 5v14M16 5v14',stop:'M6 6h12v12H6z',back:'M10 5l-7 7 7 7M3 12h18',return:'M8 4L3 9l5 5M3 9h11a6 6 0 010 12',expand:'M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',power:'M12 3v9M6.4 5.8a8 8 0 1011.2 0',volume:'M4 9h4l5-5v16l-5-5H4zM17 8a6 6 0 010 8M20 5a10 10 0 010 14',book:'M12 5c-3-2-7-2-10 0v15c3-2 7-2 10 0 3-2 7-2 10 0V5c-3-2-7-2-10 0zM12 5v15',check:'M5 12l4 4L19 6',rack:'M4 3h16v18H4zM4 9h16M4 15h16M7 6h1M7 12h1M7 18h1',network:'M9 3h6v6H9zM2 15h6v6H2zM16 15h6v6h-6zM12 9v3M5 15v-3h14v3',bench:'M3 9h18v4H3zM5 13v8M19 13v8M7 3h10v6H7z',cable:'M5 2v5M9 2v5M3 7h8v3a4 4 0 01-4 4v3a4 4 0 008 0v-3M13 10h8v4h-8z',chip:'M7 7h10v10H7zM9 2v5M15 2v5M9 17v5M15 17v5M2 9h5M2 15h5M17 9h5M17 15h5'};
 function glyph(name){return '<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="'+(paths[name]||paths.grid)+'"/></svg>';}
 function buttonIcon(id,name,label){const b=$(id);if(b)b.innerHTML=glyph(name)+'<span>'+label+'</span>';}
 // Put the compact lesson above the entire lab, keeping the bench near the top.
 const workspace=document.querySelector('.workspace');workspace.before($('coach'));buttonIcon('goalPrev','back','Back');$('goalPrev').setAttribute('aria-label','Previous lesson prompt');
 const toolbar=document.createElement('div');toolbar.className='bench-toolbar';toolbar.innerHTML='<div><strong>Hands-on workbench</strong><span>Drag to move · click to inspect · connect labeled ports</span></div><a class="net-shortcut" href="#networkWorkshop">IP &amp; Wi-Fi settings</a><button id="tidyBench">Arrange view</button><button id="benchFocus" aria-pressed="false">Expand bench</button>';document.querySelector('.lab-surface').prepend(toolbar);
 const returnZone=document.createElement('button');returnZone.id='returnZone';returnZone.className='return-zone';returnZone.innerHTML=glyph('return')+'<span><b>Return to shelf</b><small>Drop here, or click for the selected item</small></span>';toolbar.after(returnZone);
 const notice=document.createElement('div');notice.id='returnNotice';notice.hidden=true;notice.setAttribute('role','status');notice.innerHTML='<span id="returnMessage"></span><button id="undoReturn">Undo return</button><button id="dismissReturn" aria-label="Dismiss return notification">Dismiss</button>';document.body.append(notice);$('dismissReturn').onclick=()=>notice.hidden=true;
 function returnDevice(id){const owner=state(),r=api.returnToShelf(id);if(!r.ok){api.toast(r.message,false);return;}lastReturn={owner,record:r.record};api.result(r);$('returnMessage').textContent=r.message;notice.hidden=false;document.querySelector('.inspector').classList.remove('mobile-open');}
 $('undoReturn').onclick=()=>{if(!lastReturn||lastReturn.owner!==state()){notice.hidden=true;api.toast('That return belongs to a different lab session.',false);return;}const r=api.restoreFromShelf(lastReturn.record);api.result(r);if(r.ok){lastReturn=null;notice.hidden=true;}};returnZone.onclick=()=>returnDevice(state().selected);
 const mobilebar=document.createElement('nav');mobilebar.className='lab-jumps';mobilebar.setAttribute('aria-label','Lab shortcuts');mobilebar.innerHTML='<a href="#coach">Lesson</a><a href="#inventory">Equipment</a><a href="#scene">Workbench</a><a href="#devicePanel">Settings</a><a href="#testResult">Test results</a><a href="#labStudio">Lab studio</a><a href="#networkWorkshop">IP &amp; Wi-Fi</a><a href="#vmWorkshop">Virtual machines</a>';workspace.before(mobilebar);
 const close=document.createElement('button');close.id='closeInspector';close.textContent='Back to bench';document.querySelector('.inspector .section-heading').append(close);close.onclick=()=>{document.querySelector('.inspector').classList.remove('mobile-open');scene.scrollIntoView({block:'center',behavior:'smooth'})};
 const shelf=document.querySelector('.shelf');shelf.querySelector('.small').textContent='Drag out to build. Drop back here to return. Click any item to add it.';
 for(const b of $('inventory').querySelectorAll('button')){const handle=document.createElement('span');handle.className='grab-handle';handle.textContent='⠿';handle.title='Drag this equipment to the workbench';handle.setAttribute('aria-hidden','true');b.prepend(handle);b.title='Drag to place, or click to add';}
 const toolHeading=shelf.querySelectorAll('h2')[1];const tools=document.createElement('details');tools.className='shelf-group';tools.open=!window.matchMedia?.('(max-width:780px)')?.matches;tools.innerHTML='<summary>Safety & power tools</summary>';toolHeading.before(tools);tools.append($('safetyTools'),$('powerOutage'));toolHeading.remove();const saves=document.createElement('details');saves.className='shelf-group';saves.innerHTML='<summary>Save, load & reset</summary>';shelf.append(saves);for(const id of ['saveLab','loadLab','saveStatus','exportLab'])saves.append($(id));saves.append(shelf.querySelector('.file-button'),$('resetOpen'));
 $('coach').querySelector('details').id='lessonDetails';const audio=document.createElement('details');audio.id='audioOptions';audio.className='audio-options';audio.innerHTML='<summary>Voice & listening options</summary><div class="voice-options"><label>Voice<select id="narratorVoice"><option value="">Device default voice</option></select></label><label>Speed<select id="narratorRate"><option value="0.75">0.75× · slower</option><option value="0.9" selected>0.9× · clear</option><option value="1">1× · normal</option><option value="1.15">1.15× · faster</option></select></label><label class="check"><input type="checkbox" id="autoNarrate"> Read each next lesson automatically</label><label class="check"><input type="checkbox" id="readDetails" checked> Include the exact steps</label></div><p class="small">Uses the voices available in your browser. Press Play to begin. The written lesson is always available.</p>'; $('coach').append(audio);
 const pause=document.createElement('button');pause.id='pauseVoice';pause.textContent='Pause';pause.disabled=true;$('coachVoice').after(pause);$('coachVoice').textContent='▶ Play lesson';buttonIcon('coachVoice','play','Play lesson');const status=document.createElement('span');status.id='voiceStatus';status.setAttribute('role','status');status.textContent=supported?'Narration ready':'Narration unavailable in this browser';$('coach').querySelector('.coach-top').append(status);
 const readDevice=document.createElement('button');readDevice.id='readDevice';readDevice.textContent='▶ Explain selected device';document.querySelector('.inspector .section-heading').after(readDevice);
 const readTest=document.createElement('button');readTest.id='readTest';readTest.textContent='▶ Read test result';document.querySelector('.test-bench .section-heading').append(readTest);
 function setVoiceStatus(text,mode='idle'){voiceState=mode;status.textContent=text;pause.disabled=mode==='idle';buttonIcon('pauseVoice',mode==='paused'?'play':'pause',mode==='paused'?'Resume':'Pause');buttonIcon('coachVoice','play',mode==='playing'?'Replay lesson':'Play lesson');}
 function stop(){voiceToken++;window.speechSynthesis?.cancel();utterance=null;setVoiceStatus(supported?'Narration stopped':'Narration unavailable in this browser');}
 function speak(text,label='Lesson'){if(!supported)return api.toast('Narration is unavailable here. The complete text remains on screen.',false);stop();const token=voiceToken,parts=text.split(/(?<=[.!?])\s+/).filter(Boolean);let index=0;setVoiceStatus('Reading '+label.toLowerCase(),'playing');
  const next=()=>{if(token!==voiceToken)return;if(index>=parts.length){utterance=null;setVoiceStatus(label+' finished');return;}utterance=new window.SpeechSynthesisUtterance(parts[index++].trim());utterance.rate=Number($('narratorRate').value);const selected=voices.find(v=>v.voiceURI===$('narratorVoice').value);if(selected)utterance.voice=selected;utterance.onend=next;utterance.onerror=e=>{if(token!==voiceToken||e.error==='canceled'||e.error==='interrupted')return;setVoiceStatus('Voice could not play. Try another voice.');};window.speechSynthesis.speak(utterance);};next();}
 function readLesson(){const text=$('goalTitle').textContent+'. '+$('goalBody').textContent+($('readDetails').checked?' '+$('goalHelp').textContent:'');speak(text,'Lesson');}
 function fillVoices(){if(!supported)return;const current=$('narratorVoice').value;voices=window.speechSynthesis.getVoices();$('narratorVoice').replaceChildren(new Option('Device default voice',''));for(const v of voices.filter(v=>/^en/i.test(v.lang)))$('narratorVoice').add(new Option(v.name+' · '+v.lang,v.voiceURI));if([...$('narratorVoice').options].some(o=>o.value===current))$('narratorVoice').value=current;}
 fillVoices();window.speechSynthesis?.addEventListener('voiceschanged',fillVoices);
 $('coachVoice').onclick=readLesson;$('stopVoice').onclick=stop;pause.onclick=()=>{if(voiceState==='paused'){window.speechSynthesis.resume();setVoiceStatus('Narration resumed','playing')}else if(voiceState==='playing'){window.speechSynthesis.pause();setVoiceStatus('Narration paused','paused')}};
 $('readDevice').onclick=()=>{if(!state().selected)return api.toast('Select equipment on the bench first.',false);speak($('deviceTitle').textContent+'. '+$('deviceIntro').textContent,'Device explanation')};$('readTest').onclick=()=>speak($('testResult').textContent,'Test result');for(const id of ['narratorRate','narratorVoice'])$(id).onchange=()=>{if(voiceState!=='idle')stop()};
 if(!supported)for(const id of ['coachVoice','pauseVoice','stopVoice','readDevice','readTest','autoNarrate','narratorVoice','narratorRate'])$(id).disabled=true;
 // Auto narration follows user navigation, never configuration re-renders.
 function onLesson(){const k=state().mission+':'+state().step;if(k!==spokenStep){const hadStep=spokenStep!=='';spokenStep=k;if(hadStep){stop();if($('autoNarrate').checked)readLesson();}}}
 function organizeInspector(){const panel=$('devicePanel');if(!panel.firstChild)return;const id=state().selected;if(inspected!==id){activeSection='Ports & cables';inspected=id;document.querySelector('.inspector').scrollTop=0;}let group=null;for(const child of [...panel.children]){if(child.tagName==='H3'){const title=child.textContent;group=document.createElement('details');group.className='inspector-group';group.open=title===activeSection;const sum=document.createElement('summary');sum.textContent=title;group.append(sum);child.before(group);child.remove();const section=group;section.addEventListener('toggle',()=>{if(section.open)activeSection=title});}else if(child.tagName==='HR'||child.id==='removeDevice'){group=null;}else if(group)group.append(child);}
 const power=$('togglePower');if(power){power.classList.add('power-button');buttonIcon('togglePower','power',power.textContent);}buttonIcon('removeDevice','return','Return to equipment shelf');
 }
 function drawWires(overrides={}){if(api.drawCables){api.drawCables(overrides);return;}const map={...api.positions(),...overrides},height=parseFloat(scene.style.height)||640;for(const p of $('wires').querySelectorAll('path[data-link]')){const l=state().links.find(l=>l.id===p.dataset.link);if(!l)continue;const locate=(id,port)=>{const base=api.positions()[id],p=api.portPosition?api.portPosition(id,port):base,shift=overrides[id];return shift&&base?[p[0]+shift[0]-base[0],p[1]+shift[1]-base[1]]:p;};const a=locate(l.a,l.ap),b=locate(l.b,l.bp);if(!a||!b)continue;p.setAttribute('d',`M${a[0]*10},${a[1]*height/100} C${a[0]*10},${(a[1]+12)*height/100} ${b[0]*10},${(b[1]+12)*height/100} ${b[0]*10},${b[1]*height/100}`);const adapter=$('wires').querySelector(`[data-adapter-link="${l.id}"]`);adapter?.setAttribute('transform',`translate(${(a[0]+b[0])*5},${(a[1]+b[1])*height/200+.09*height})`);}}
 function savePosition(id,point){const s=state();s.layout??={};s.layout[s.view]??={};s.layout[s.view][id]=point;}
 function refreshDrag(){raf=0;if(!drag?.moving)return;const r=scene.getBoundingClientRect(),x=(drag.cx-r.left)/r.width*100,y=(drag.cy-r.top)/r.height*100;drag.inside=drag.cx>=r.left&&drag.cx<=r.right&&drag.cy>=r.top&&drag.cy<=r.bottom;const viewport=$('benchViewport');if(viewport){const vr=viewport.getBoundingClientRect();drag.inside=drag.inside&&drag.cx>=vr.left&&drag.cx<=vr.right&&drag.cy>=vr.top&&drag.cy<=vr.bottom;}const hit=el=>{const q=el.getBoundingClientRect();return q.width>0&&q.height>0&&drag.cx>=q.left&&drag.cx<=q.right&&drag.cy>=q.top&&drag.cy<=q.bottom;};drag.returning=!!drag.id&&(hit(shelf)||hit(returnZone));shelf.classList.toggle('return-ready',drag.returning);returnZone.classList.toggle('return-ready',drag.returning);drag.point=clampPoint(x-drag.offsetX,y-drag.offsetY);scene.classList.toggle('drop-ready',drag.inside);if(drag.ghost)drag.ghost.style.transform=`translate3d(${drag.cx-(drag.ghostOffsetX??56)}px,${drag.cy-(drag.ghostOffsetY??55)}px,0)`;if(drag.id&&drag.inside&&!drag.returning)drawWires({[drag.id]:drag.point});}
 function cleanup(){if(raf)cancelAnimationFrame(raf);raf=0;drag?.ghost?.remove();drag?.node?.classList.remove('dragging');scene.classList.remove('drop-ready');shelf.classList.remove('return-ready');returnZone.classList.remove('return-ready');document.body.classList.remove('lab-dragging');drag=null;}
 function cancel(){if(!drag)return;const moved=drag.moving;cleanup();if(moved){suppressUntil=Date.now()+350;api.renderScene();api.toast('Placement canceled. Equipment stays where it was.')}}
 document.addEventListener('pointerdown',e=>{if(e.button!==0||drag||e.target.closest('[data-bench-port],[data-bench-plug],[data-bench-power]'))return;const hit=e.target.closest('[data-add],[data-device]'),node=hit?.closest('.physical-device')||hit;if(!node)return;if(e.pointerType==='touch'&&node.dataset.add&&!e.target.closest('.grab-handle'))return;const id=node.dataset.device,d=id?state().devices.find(d=>d.id===id):null;if(d&&['wall','isp'].includes(d.type))return;if(!['bench','rear','network','rack'].includes(state().view)){return;}const rect=scene.getBoundingClientRect(),p=id?api.positions()[id]:null;drag={node,id,type:node.dataset.add,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,cx:e.clientX,cy:e.clientY,moving:false,offsetX:p?(e.clientX-rect.left)/rect.width*100-p[0]:0,offsetY:p?(e.clientY-rect.top)/rect.height*100-p[1]:0};node.setPointerCapture?.(e.pointerId);});
 document.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;drag.cx=e.clientX;drag.cy=e.clientY;if(!drag.moving&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>6){drag.moving=true;document.body.classList.add('lab-dragging');const ghost=drag.node.cloneNode(true);ghost.removeAttribute('id');ghost.removeAttribute('style');ghost.removeAttribute('data-add');ghost.removeAttribute('data-device');ghost.className='drag-ghost '+(drag.id?'device-ghost':'shelf-ghost');ghost.setAttribute('aria-hidden','true');if(drag.node.classList.contains('physical-device')){const r=drag.node.getBoundingClientRect();ghost.style.width=r.width+'px';ghost.style.transformOrigin='top left';drag.ghostOffsetX=drag.startX-r.left;drag.ghostOffsetY=drag.startY-r.top;}document.body.append(ghost);drag.ghost=ghost;if(drag.id)drag.node.classList.add('dragging');}if(drag.moving){e.preventDefault();if(!raf)raf=requestAnimationFrame(refreshDrag);}}, {passive:false});
 document.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointerId)return;if(!drag.moving){cleanup();return;}drag.cx=e.clientX;drag.cy=e.clientY;refreshDrag();const {inside,point,type,id,returning}=drag;suppressUntil=Date.now()+450;cleanup();if(returning){returnDevice(id);return;}if(state().view==='rack'){api.renderScene();api.toast('Use Rack placement in the device settings to choose checked rack units. Drag to the shelf to return an item.');return;}if(!inside){api.renderScene();api.toast('Drop inside the workbench. Nothing was moved.',false);return;}if(type){const r=api.addDevice(type);if(!r.ok){api.result(r);return;}state().selected=r.id;savePosition(r.id,point);api.result({...r,message:'Placed on the bench. Select its picture to connect power and data.'});}else{savePosition(id,point);state().selected=id;api.renderScene();api.renderInspector();api.toast('Position saved. Cables stay connected.');} });
 document.addEventListener('pointercancel',cancel);window.addEventListener('blur',cancel);document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancel();document.querySelector('.inspector').classList.remove('mobile-open');}if(e.target.closest?.('[data-bench-port],[data-bench-plug],[data-bench-power]'))return;const node=e.target.closest?.('[data-device]');if(!node||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||!['bench','rear','network'].includes(state().view))return;const d=state().devices.find(d=>d.id===node.dataset.device);if(!d||['wall','isp'].includes(d.type))return;e.preventDefault();const p=api.positions()[d.id],step=e.shiftKey?5:1;savePosition(d.id,clampPoint(p[0]+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),p[1]+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0)));api.renderScene();document.querySelector(`[data-device="${d.id}"]`)?.focus();});
 document.addEventListener('click',e=>{if(Date.now()<suppressUntil&&e.target.closest('[data-add],[data-device]')){e.preventDefault();e.stopImmediatePropagation();}},true);
 document.addEventListener('dragstart',e=>{if(e.target.closest('[data-device],[data-add]'))e.preventDefault()});
 $('tidyBench').onclick=()=>{if(state().layout)delete state().layout[state().view];api.renderScene();api.toast('This view is arranged. Saved connections are unchanged.')};$('benchFocus').onclick=()=>{const active=workspace.classList.toggle('bench-expanded');$('benchFocus').setAttribute('aria-pressed',active);buttonIcon('benchFocus','expand',active?'Show panels':'Expand bench')};
 function revealInspector(){workspace.classList.remove('bench-expanded');$('benchFocus').setAttribute('aria-pressed','false');buttonIcon('benchFocus','expand','Expand bench');if(window.matchMedia?.('(max-width:1250px)')?.matches)document.querySelector('.inspector').classList.add('mobile-open');}
 for(const link of document.querySelectorAll('a[href="#devicePanel"]'))link.onclick=e=>{e.preventDefault();revealInspector();};
 for(const [id,name,label]of [['tidyBench','grid','Arrange'],['benchFocus','expand','Expand bench'],['stopVoice','stop','Stop'],['pauseVoice','pause','Pause'],['readDevice','volume','Explain device'],['readTest','volume','Read test result'],['helpOpen','book','Lab manual'],['glossaryOpen','book','Glossary'],['closeInspector','back','Back to bench'],['newLab','play','Start lab']])buttonIcon(id,name,label);
 for(const b of document.querySelectorAll('[data-view]')){const label=b.textContent;b.innerHTML=glyph({bench:'bench',rack:'rack',rear:'cable',network:'network',inside:'chip'}[b.dataset.view])+'<span>'+label+'</span>';}
 const brand=document.querySelector('.brand-icon');if(brand)brand.innerHTML=glyph('network');
 window.addEventListener('resize',()=>{if(!drag)api.renderScene()});window.addEventListener('pagehide',stop);organizeInspector();onLesson();return {organizeInspector,onLesson,stop,speak,revealInspector,returnDevice};
}
