import * as E from './lab-engine.js?v=desktop36';
import {context,address,changeAddress,request,runCommand,subnet} from './lab-os-engine.js?v=desktop36';
import {lessons,projects,references} from './lab-learning-repos.js?v=desktop36';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={start:'<path d="M3 3h8v8H3zm10 0h8v8h-8zM3 13h8v8H3zm10 0h8v8h-8z"/>',repos:'<path d="M2 6h8l2 2h10v13H2z"/><path d="M2 6V3h8l2 3"/>',terminal:'<rect x="2" y="3" width="20" height="18" rx="3"/><path d="m6 8 4 4-4 4m7 0h5"/>',settings:'<circle cx="12" cy="12" r="4"/><path d="M12 1v4m0 14v4M1 12h4m14 0h4M4 4l3 3m10 10 3 3M4 20l3-3M17 7l3-3"/>',browser:'<circle cx="12" cy="12" r="10"/><ellipse cx="12" cy="12" rx="4" ry="10"/><path d="M2 12h20"/>',vms:'<rect x="1" y="2" width="15" height="13" rx="2"/><rect x="8" y="9" width="15" height="13" rx="2"/>',cloud:'<path d="M6 19a5 5 0 0 1-1-10 7 7 0 0 1 13-2 6 6 0 0 1 0 12Z"/>',tools:'<rect x="3" y="3" width="18" height="14" rx="2"/><path d="M12 17v4m-5 0h10M6 7h12M6 11h7"/>'};
const icon=k=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[k]||icons.repos}</svg>`;
const apps={repos:'Learning repositories',terminal:'Terminal',settings:'Settings',browser:'Browser',vms:'Virtual machines',cloud:'Cloud console',tools:'System tools'};
export function setupDesktop(api){
 const state=()=>api.getState();let machine=null,owner=state(),app='repos',folder='home',lessonId=null,projectId=null,shell='powershell',log=[],history=[],historyIndex=0,notice='',maximized=false,minimized=false,guide=true,settingsTab='network',lastFocus=null,quizFeedback='',pageResult=null,windowPosition=null;
 const dialog=document.createElement('dialog');dialog.id='osDesktop';dialog.setAttribute('aria-label','Simulated operating system desktop');document.body.append(dialog);
 const $=id=>dialog.querySelector('#'+id),ctx=()=>context(state(),machine),ubuntu=()=>ctx().os==='ubuntu';
 const progress=()=>{state().desktopProgress??={opened:false,machines:{}};state().desktopProgress.machines??={};return state().desktopProgress.machines[machine]??={commands:[],quizzes:[],projects:[]};};
 const field=(id,label,value,type='text')=>`<label for="${id}">${label}<input id="${id}" type="${type}" value="${esc(value)}" autocomplete="off"></label>`;
 function open(id){const c=context(state(),id);if(!c.status?.ok){api.result({ok:false,message:c.status?.why||'Power on and boot this computer first.'});return;}lastFocus=document.activeElement;machine=id;owner=state();app='repos';folder='home';lessonId=projectId=null;shell=c.os==='ubuntu'?'bash':'powershell';log=[];history=[];pageResult=null;notice='';windowPosition=null;maximized=false;minimized=false;state().desktopProgress??={opened:false,machines:{}};state().desktopProgress.opened=true;progress();draw();if(!dialog.open)dialog.showModal();dialog.querySelector('[data-osapp="repos"]')?.focus();api.render?.();}
 function close(){dialog.close();lastFocus?.focus?.();api.render?.();}
 function openApp(name){app=name;minimized=false;notice='';quizFeedback='';draw();if(app==='terminal')$('osCommand')?.focus();}
 function shellName(){return shell==='bash'?'student@home-lab:~$':shell==='cmd'?'C:\\Users\\Student>':'PS C:\\Users\\Student>';}
 function draw(){if(!machine)return;const c=ctx(),isUbuntu=c.os==='ubuntu';dialog.className='os-desktop '+(isUbuntu?'os-ubuntu':'os-windows');
 dialog.innerHTML=`<header class="os-simulation-bar"><div><b>${esc(c.vm?c.vm.name:c.device?.name)}</b><span>${isUbuntu?'Ubuntu 24.04 LTS-style':c.device?.os==='Hypervisor'?'Windows-style host console':c.device?.os==='Windows Server'?'Windows Server-style':'Windows 11-style'} · learning simulation</span></div><div><button id="osGuideToggle" aria-pressed="${guide}">${guide?'✓ Guidance on':'Guidance off'}</button><button id="osSave">Save progress</button><button id="osReturn">Return to 3D lab ↗</button></div></header><div class="os-workspace"><div class="os-topline"><b>${isUbuntu?'Activities':'Home Lab Desktop'}</b><span>${isUbuntu?'Ubuntu':'Windows'} · ${c.vm?'Guest VM':'Lab computer'}</span><button data-osapp="settings">${address(state(),machine).ok?'● Connected':'○ Check network'}</button></div><div class="os-wallpaper" aria-hidden="true"><i></i><i></i><i></i></div><nav class="os-desktop-icons" aria-label="Desktop shortcuts">${['repos','terminal','settings','browser','vms','cloud'].map(k=>`<button data-osapp="${k}" title="Open ${apps[k]}">${icon(k)}<span>${apps[k]}</span></button>`).join('')}</nav>${c.status.ok?`<section class="os-window ${maximized?'os-maximized':''}" ${minimized?'hidden':''} style="${!maximized&&windowPosition?`--os-dx:${windowPosition.x}px;--os-dy:${windowPosition.y}px`:''}" aria-label="${apps[app]} window"><header class="os-titlebar"><div>${icon(app)}<b>${apps[app]}</b></div><div class="os-window-controls"><button id="osMinimize" aria-label="Minimize window">─</button><button id="osMaximize" aria-label="${maximized?'Restore':'Maximize'} window">□</button><button id="osCloseApp" aria-label="Close application">×</button></div></header><div class="os-app-body">${renderApp()}</div></section>`:`<section class="os-power-off"><h2>Computer unavailable</h2><p>${esc(c.status.why)}</p><button id="osPowerReturn">Return to the lab and restore it</button></section>`}<nav class="os-taskbar" aria-label="${isUbuntu?'Ubuntu dock':'Windows taskbar'}"><button id="osStart" aria-label="${isUbuntu?'Show applications':'Start menu'}">${icon('start')}</button>${Object.entries(apps).map(([k,t])=>`<button data-osapp="${k}" class="${app===k&&!minimized?'active':''}" aria-label="Open ${t}" title="${t}">${icon(k)}</button>`).join('')}<span class="os-clock">LOCAL SIMULATION</span></nav><div id="osStartMenu" class="os-start-menu" hidden><h2>${isUbuntu?'Applications':'Pinned apps'}</h2><div>${Object.entries(apps).map(([k,t])=>`<button data-osapp="${k}">${icon(k)}${t}</button>`).join('')}</div><p>Student · no sign-in required</p></div></div>`;
 $('osReturn').onclick=close;$('osSave').onclick=()=>{const saved=api.save?.();$('osSave').textContent=saved?'Saved with this build':'Save unavailable · export from lab';};$('osPowerReturn')?.addEventListener('click',close);$('osGuideToggle').onclick=()=>{guide=!guide;draw()};$('osStart').onclick=()=>{$('osStartMenu').hidden=!$('osStartMenu').hidden};
 $('osMinimize')?.addEventListener('click',()=>{minimized=true;draw()});$('osCloseApp')?.addEventListener('click',()=>{minimized=true;draw()});$('osMaximize')?.addEventListener('click',()=>{maximized=!maximized;windowPosition=null;draw()});
 for(const b of dialog.querySelectorAll('[data-osapp]'))b.onclick=()=>openApp(b.dataset.osapp);
 bindApp();bindDrag();
 }
 const help=(title,text)=>guide?`<aside class="os-coach"><b>${title}</b><p>${text}</p></aside>`:'';
 const feedback=()=>notice?`<p class="os-notice" role="status">${esc(notice)}</p>`:'';
 function renderApp(){if(app==='terminal')return terminal();if(app==='settings')return settings();if(app==='browser')return browser();if(app==='vms')return vms();if(app==='cloud')return cloud();if(app==='tools')return tools();return repos();}
 function terminal(){return `<div class="os-terminal-tabs">${(ubuntu()?['bash']:['powershell','cmd']).map(k=>`<button data-shell="${k}" aria-pressed="${shell===k}">${k==='cmd'?'Command Prompt':k==='bash'?'Ubuntu · Bash':'Windows PowerShell'}</button>`).join('')}<button id="osCommandHelp">Command reference</button></div>${help('Your first command','Type help and press Enter. Read a setting before changing it. Use ↑ and ↓ to recall commands. Only the documented commands are simulated.')}<div class="os-terminal" aria-label="Terminal output"><p>${ubuntu()?'Ubuntu learning console':'Windows learning console'} · ${shell.toUpperCase()}<br>All output is simulated from this lab. Type help to begin.</p>${log.map(r=>`<div class="os-terminal-entry"><b>${esc(r.prompt)} ${esc(r.command)}</b><pre class="${r.ok?'':'os-command-error'}">${esc(r.output)}</pre></div>`).join('')}<form id="osTerminalForm"><label for="osCommand">${esc(shellName())}</label><input id="osCommand" aria-label="Terminal command" autocomplete="off" autocapitalize="off" spellcheck="false" maxlength="600"><button type="submit">Run ↵</button></form></div>`;}
 function settings(){const c=ctx(),n=address(state(),machine),raw=c.device?.network||{},val={...raw,...(n.ok?n:{})};return `<div class="os-settings-layout"><nav aria-label="Settings categories"><b>Settings</b><button data-setting="network" class="${settingsTab==='network'?'selected':''}">${ubuntu()?'Network':'Network & internet'}</button><button data-setting="wifi">Wi-Fi</button><button data-setting="about">System · About</button></nav><div class="os-settings-content"><p class="os-breadcrumb">Settings › ${settingsTab==='about'?'System':settingsTab==='wifi'?'Wi-Fi':ubuntu()?'Network › Wired › IPv4':'Network & internet › Ethernet'}</p><h2>${settingsTab==='about'?'About this machine':settingsTab==='wifi'?'Wi-Fi':'IP assignment'}</h2>${feedback()}${settingsTab==='about'?`<dl class="os-properties"><dt>Operating system profile</dt><dd>${ubuntu()?'Ubuntu 24.04 LTS':c.device?.os==='Hypervisor'?'Windows-style hypervisor management console':c.device?.os==='Windows Server'?'Windows Server desktop':'Windows 11 desktop'}</dd><dt>Machine</dt><dd>${esc(c.vm?.name||c.device.name)}</dd><dt>Role</dt><dd>${c.vm?'Virtual guest on '+esc(E.find(state(),c.vm.host)?.name):'Physical lab computer'}</dd><dt>Scope</dt><dd>This is a browser simulation. No real OS kernel, installation or device access.</dd></dl>`:settingsTab==='wifi'?wifiSettings():`${help('Four settings, four jobs','Address = this interface. Mask = its local network. Gateway = exit to other networks. DNS = name directory. Save, then read the result in Terminal.')}<div class="os-connection-status"><b>${n.ok?'Connected configuration':'Needs attention'}</b><p>${esc(n.why)}</p></div><form id="osNetworkForm"><label for="osIpMode">${ubuntu()?'IPv4 method':'Edit IP settings'}<select id="osIpMode"><option value="dhcp" ${raw.mode==='dhcp'?'selected':''}>Automatic (DHCP)</option><option value="static" ${raw.mode==='static'?'selected':''}>Manual</option></select></label><div id="osStaticFields" class="os-field-grid" ${raw.mode==='dhcp'?'hidden':''}>${field('osIp','IPv4 address',val.ip||'192.168.50.200')}${field('osMask','Subnet mask',val.mask||'255.255.255.0')}${field('osGateway','Default gateway',val.gateway||'192.168.50.1')}${field('osDns','Preferred DNS',val.dns||'192.168.50.1')}</div><button type="submit" class="os-primary">${ubuntu()?'Apply':'Save'}</button></form><dl class="os-properties"><dt>IPv4 address</dt><dd>${esc(n.ip||'Unavailable')}</dd><dt>Subnet mask</dt><dd>${esc(n.mask||'Unavailable')}</dd><dt>Gateway</dt><dd>${esc(n.gateway||'None')}</dd><dt>DNS</dt><dd>${esc(n.dns||'None')}</dd></dl><button data-osapp="terminal">Verify in Terminal →</button>`}</div></div>`;}
 function wifiSettings(){const c=ctx();if(c.vm||c.device.type!=='laptop')return '<p>This machine has a wired virtual or server adapter. Practice Wi-Fi on the physical laptop; a VM does not automatically inherit the host’s radio controls.</p>';const aps=E.ofType(state(),'ap').filter(a=>E.powered(state(),a.id));return `${help('Join first. Get an address second.','Build and power the access point and its switch uplink. Select its SSID below. Use a teaching passphrase, not a personal password.')}<p>Active connection: ${c.device.network.wifi?esc(c.device.network.ssid||'No SSID'):'Ethernet'}</p><form id="osWifiForm"><label for="osSsid">Available networks<select id="osSsid">${aps.map(a=>`<option value="${esc(a.ssid)}" ${a.ssid===c.device.network.ssid?'selected':''}>${esc(a.ssid)} · ${a.band} GHz · ${esc(a.security)}</option>`).join('')}</select></label>${!aps.length?'<p>No powered access point found. Return to the lab and connect its power/uplink.</p>':''}${field('osWifiPassword','Network security key / password','','password')}<button class="os-primary" ${aps.length?'':'disabled'}>Connect</button><button type="button" id="osEthernet">Use Ethernet instead</button></form><p>${esc(E.wifiAssociation(state(),machine).why)}</p>`;}
 function browser(){return `${help('Test the real simulated path','This teaching browser opens one modeled public page. It checks this computer’s power, address, routing, DNS and HTTPS path. It does not browse the external Internet.')}<form id="osBrowserForm" class="os-address-bar"><label for="osUrl">Address</label><input id="osUrl" value="https://example.com" autocomplete="off"><button class="os-primary">Go</button></form>${pageResult?`<div class="os-browser-result ${pageResult.ok?'pass':'fail'}"><span>${pageResult.ok?'✓':'!'}</span><h2>${pageResult.ok?'Example page received':'This page could not load'}</h2><p>${esc(pageResult.why)}</p><ol>${(pageResult.trace||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p>This is a teaching response, not a live website or a latency measurement.</p></div>`:'<div class="os-browser-empty">'+icon('browser')+'<h2>Follow a request from this computer</h2><p>Press Go. Watch where the path succeeds or stops.</p></div>'}`;}
 function repos(){const p=progress();if(lessonId){const l=lessons.find(x=>x.id===lessonId);return `<div class="os-repo-toolbar"><button id="osRepoBack">← Foundations</button><span>Learning-Repositories / 01-Foundations</span></div><article class="os-lesson"><p class="os-eyebrow">${esc(l.level)} · ${lessons.indexOf(l)+1} / ${lessons.length}</p><h2>${esc(l.title)}</h2><p class="os-lede">${esc(l.summary)}</p><ol class="os-workflow">${l.path.map((x,i)=>`<li><b>${i+1}</b><span>${esc(x)}</span></li>`).join('')}</ol>${l.sections.map(([h,t])=>`<section><h3>${esc(h)}</h3><p>${esc(t)}</p></section>`).join('')}${l.id==='subnet'?subnetTool():''}<div class="os-try"><b>Try it in this computer’s Terminal</b><code>${esc(l.commands[ubuntu()?'ubuntu':'windows'])}</code><button id="osTryCommand">Load command into Terminal</button><small>Loading does not run the command. Press Enter when you are ready.</small></div><fieldset class="os-quiz"><legend>Check your understanding: ${esc(l.quiz[0])}</legend>${l.quiz[1].map((a,i)=>`<button data-quiz="${i}">${esc(a)}</button>`).join('')}<p role="status">${esc(quizFeedback|| (p.quizzes.includes(l.id)?'✓ Answered correctly on this build.':''))}</p></fieldset><p class="os-sources">Read more: ${l.refs.map(k=>`<a href="${references[k][1]}" target="_blank" rel="noopener">${esc(references[k][0])}</a>`).join(' · ')}</p><div class="os-lesson-nav">${lessons.indexOf(l)>0?'<button id="osPreviousLesson">← Previous lesson</button>':''}${lessons.indexOf(l)<lessons.length-1?'<button id="osNextLesson" class="os-primary">Next lesson →</button>':''}</div><p class="os-small">Original lessons aligned with A+ networking, operating systems and virtualization topics. Subnet arithmetic and VLAN exercises include extension practice. These are not official CompTIA exam questions.</p></article>`;}
 if(projectId){const project=projects.find(x=>x.id===projectId);return `<div class="os-repo-toolbar"><button id="osProjectBack">← Practice projects</button><span>02-Practice-Projects</span></div><article class="os-lesson"><p class="os-eyebrow">DO → OBSERVE → VERIFY</p><h2>${esc(project.title)}</h2><p class="os-lede">${esc(project.task)}</p>${feedback()}<button id="osProjectApp" class="os-primary">Open ${apps[project.app]}</button><button id="osCheckProject">Check this project</button><button data-lesson="${project.lesson}">Explain the concept</button><p>${p.projects.includes(project.id)?'✓ Completed on this build. You can repeat it.':'Come back to this project and check after doing the task.'}</p><p class="os-small">Project checks use current lab state and successful commands, not a timer. Follow the guided build first if its required equipment is missing.</p></article>`;}
 return `<div class="os-repo-toolbar"><button id="osRepoHome">⌂ Home</button><span>Learning-Repositories ${folder==='home'?'':' / '+(folder==='foundations'?'01-Foundations':'02-Practice-Projects')}</span><label class="os-search">Find a lesson<input id="osRepoSearch" type="search" placeholder="IP, mask, Wi-Fi, cloud…"></label></div><div class="os-repo-content"><p class="os-eyebrow">YOUR IN-COMPUTER LEARNING LIBRARY</p><h2>${folder==='home'?'Start small. Build understanding.':folder==='foundations'?'01 · Foundations':'02 · Practice projects'}</h2>${folder==='home'?`${help('New here? Start with Foundations','Read lesson 01, follow the numbered workflow, and try the command. After the first few lessons, open Practice projects. Everything you need stays inside this desktop.')}<div class="os-folders"><button data-folder="foundations">${icon('repos')}<b>01 · Foundations</b><span>12 short lessons · definitions · workflow maps · questions</span></button><button data-folder="projects">${icon('terminal')}<b>02 · Practice projects</b><span>8 hands-on tasks · live checks · repeat anytime</span></button></div><p>Progress: ${p.quizzes.length} / 12 knowledge checks · ${p.projects.length} / 8 projects. Use Save my progress in the lab to keep this with your build.</p><p class="os-small">These are virtual learning folders packaged with the simulator. No Git account, download or external terminal is required.</p>`:`<div id="osRepoItems" class="os-repo-grid">${folder==='foundations'?lessons.map(l=>`<button data-lesson="${l.id}" data-search="${esc([l.title,l.summary,...l.sections.flat()].join(' ').toLowerCase())}"><span class="os-file-icon">${p.quizzes.includes(l.id)?'✓':'≡'}</span><b>${esc(l.title)}</b><span>${esc(l.summary)}</span><small>${esc(l.level)}</small></button>`).join(''):projects.map(pj=>`<button data-project="${pj.id}" data-search="${esc((pj.title+' '+pj.task).toLowerCase())}"><span class="os-file-icon">${p.projects.includes(pj.id)?'✓':'▸'}</span><b>${esc(pj.title)}</b><span>${esc(pj.task)}</span></button>`).join('')}</div><p id="osSearchEmpty" hidden>No matching lessons. Try a shorter word.</p>`}</div>`;}
 function subnetTool(){return `<section class="os-subnet"><h3>Subnet workbench</h3><p>Move the network/host boundary. Watch the address range change.</p><form id="osSubnetForm" class="os-field-grid">${field('osSubnetIp','IPv4 address','192.168.50.100')}<label>Network bits / prefix<input id="osPrefix" type="number" min="0" max="32" value="24"></label><button class="os-primary">Calculate</button></form><div id="osSubnetResult" aria-live="polite"></div></section>`;}
 function vms(){const hosts=E.ofType(state(),'server');return `<div class="os-manager"><h2>Virtual Machine Manager</h2>${help('A VM needs a prepared host','Build the server in the guided lab first. Create the guest, install its Linux OS, start it, then Open Ubuntu desktop. External reaches the LAN. Private and Internal have no Internet route here.')}${feedback()}<form id="osCreateVm" class="os-field-grid"><label>Host<select id="osVmHost">${hosts.map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('')}</select></label>${field('osVmName','Guest name','Ubuntu-Lab')}${field('osVmRam','RAM · GB',4,'number')}${field('osVmCpu','vCPUs',2,'number')}${field('osVmDisk','Disk · GB',40,'number')}<button class="os-primary" ${hosts.length?'':'disabled'}>Create Ubuntu VM definition</button></form>${state().vms.map(v=>{const r=E.vmStatus(state(),v);return `<article class="os-vm-row"><h3>${esc(v.name)}</h3><p>${esc(r.why)}</p><p>${v.cpu} vCPUs · ${v.ram} GB RAM · ${v.disk} GB disk</p><div class="os-vm-buttons"><button data-guest-install="${v.id}" ${v.os?'disabled':''}>${v.os?'OS installed':'Install Ubuntu guest OS'}</button><button data-guest-run="${v.id}" ${v.os?'':'disabled'}>${v.running?'Stop VM':'Start VM'}</button><button data-guest-open="${v.id}" ${r.ok?'':'disabled'}>Open Ubuntu desktop</button><label>Virtual switch<select data-guest-switch="${v.id}">${['external','internal','private'].map(k=>`<option ${v.mode===k?'selected':''}>${k}</option>`).join('')}</select></label></div></article>`}).join('')||'<p>No guests yet. Your host must be powered, have its parts, healthy storage, a hypervisor and firmware virtualization enabled.</p>'}</div>`;}
 function cloud(){const s=state(),cl=s.cloud;return `<div class="os-manager"><h2>Cloud learning console</h2>${help('Choose what you manage','IaaS: manage the OS and app. PaaS: manage your code and data. SaaS: use the provider’s app. This console only creates a teaching record, never a real account or bill.')}${feedback()}<form id="osCloudForm" class="os-field-grid"><label>Deployment<select id="osCloudModel">${['public','private','hybrid','community'].map(k=>`<option ${cl.model===k?'selected':''}>${k}</option>`).join('')}</select></label><label>Service model<select id="osCloudService">${['iaas','paas','saas'].map(k=>`<option value="${k}" ${cl.service===k?'selected':''}>${k.toUpperCase()}</option>`).join('')}</select></label><button class="os-primary">Provision learning account</button></form><h3>Separate recovery copy</h3><label>Source server / NAS<select id="osBackupSource">${s.devices.filter(d=>['server','nas'].includes(d.type)).map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></label><button id="osBackup">Run simulated off-site backup</button><button id="osVerifyBackup" ${cl.backup?'':'disabled'}>Verify recovery record</button><p>${cl.backup?'Recovery copy: '+esc(cl.sourceName)+(cl.verified?' · verified':' · verification needed'):'No recovery copy yet.'}</p><button data-lesson="cloud">Explain cloud models →</button></div>`;}
 function tools(){const c=ctx(),d=c.device;return `<div class="os-manager"><h2>${ubuntu()?'System information':'Computer Management · teaching view'}</h2>${help('Match the tool to the question','Device Manager shows hardware and driver status. Services shows background processes. This window reads modeled facts only; it does not invent CPU or network performance graphs.')}<h3>Device Manager · network adapter</h3><dl class="os-properties"><dt>Adapter</dt><dd>${c.vm?'Virtual Ethernet adapter':esc(d.nic||'None')}</dd><dt>Driver</dt><dd>${d.drivers?'Loaded in the model':'Missing'}</dd><dt>Address status</dt><dd>${esc(address(state(),machine).why)}</dd></dl><h3>Services</h3><table><thead><tr><th>Service</th><th>Status</th><th>Listening endpoint</th></tr></thead><tbody><tr><td>Lab HTTPS</td><td>${(c.vm?c.vm.service:d.services.web)?'Running':'Stopped'}</td><td>TCP 443 when running</td></tr><tr><td>Lab SMB</td><td>${d.services.file?'Running':'Stopped'}</td><td>TCP 445 when running</td></tr></tbody></table><button data-osapp="terminal">Inspect listening ports in Terminal</button><button data-lesson="windows">Learn Windows tools</button></div>`;}
 function recordCommand(command,r){if(!r.ok)return;const p=progress();if(/^(Get-NetIPConfiguration|ipconfig(?: \/all)?|ip addr|ip address|nmcli device show)$/i.test(command))p.commands.push('read');if(/^(Resolve-DnsName|nslookup|resolvectl query) example\.com$/i.test(command))p.commands.push('dns');if(command==='ss -lnt')p.commands.push('ports');p.commands=[...new Set(p.commands)];}
 function checkProject(p){const c=ctx(),n=address(state(),machine),prog=progress();const checks={read:()=>prog.commands.includes('read'),static:()=>n.ok&&c.device.network.mode==='static',dns:()=>prog.commands.includes('dns'),page:()=>prog.page===true&&request(state(),machine).ok,automatic:()=>n.ok&&c.device.network.mode==='dhcp',wifi:()=>!c.vm&&c.device.network.wifi&&request(state(),machine).ok,service:()=>!!c.vm&&c.vm.service&&prog.commands.includes('ports')&&state().devices.some(d=>d.type==='laptop'&&E.testVM(state(),d.id,machine).ok),cloud:()=>state().cloud.backup&&state().cloud.verified};const passed=!!checks[p.check]?.();if(passed&&!prog.projects.includes(p.id))prog.projects.push(p.id);return passed;}
 function bindApp(){for(const b of dialog.querySelectorAll('[data-shell]'))b.onclick=()=>{shell=b.dataset.shell;draw();$('osCommand').focus()};$('osCommandHelp')?.addEventListener('click',()=>execute('help'));
 $('osTerminalForm')?.addEventListener('submit',e=>{e.preventDefault();execute($('osCommand').value)});$('osCommand')?.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();historyIndex=Math.max(0,Math.min(history.length,historyIndex+(e.key==='ArrowUp'?-1:1)));e.target.value=history[historyIndex]||'';}});
 for(const b of dialog.querySelectorAll('[data-setting]'))b.onclick=()=>{settingsTab=b.dataset.setting;notice='';draw()};$('osIpMode')?.addEventListener('change',e=>{$('osStaticFields').hidden=e.target.value==='dhcp'});
 $('osNetworkForm')?.addEventListener('submit',e=>{e.preventDefault();const mode=$('osIpMode').value,r=changeAddress(state(),machine,mode==='dhcp'?{mode}:{mode,ip:$('osIp').value.trim(),mask:$('osMask').value.trim(),gateway:$('osGateway').value.trim(),dns:$('osDns').value.trim()});notice=r.message;if(r.ok)api.render?.();draw()});
 $('osWifiForm')?.addEventListener('submit',e=>{e.preventDefault();const d=ctx().device,r=changeAddress(state(),machine,{mode:d.network.mode,wifi:true,ssid:$('osSsid').value,password:$('osWifiPassword').value});const a=E.wifiAssociation(state(),machine);notice=a.ok?'Joined. '+address(state(),machine).why:a.why;api.render?.();draw()});$('osEthernet')?.addEventListener('click',()=>{const r=changeAddress(state(),machine,{mode:ctx().device.network.mode,wifi:false});notice=r.message;api.render?.();draw()});
 $('osBrowserForm')?.addEventListener('submit',e=>{e.preventDefault();pageResult=/^https:\/\/example\.com\/?$/i.test($('osUrl').value.trim())?request(state(),machine):{ok:false,why:'Only https://example.com is modeled here.'};if(pageResult.ok)progress().page=true;draw()});
 for(const b of dialog.querySelectorAll('[data-folder]'))b.onclick=()=>{folder=b.dataset.folder;lessonId=projectId=null;draw()};for(const b of dialog.querySelectorAll('[data-lesson]'))b.onclick=()=>{app='repos';folder='foundations';lessonId=b.dataset.lesson;projectId=null;quizFeedback='';draw()};for(const b of dialog.querySelectorAll('[data-project]'))b.onclick=()=>{projectId=b.dataset.project;lessonId=null;notice='';draw()};
 $('osRepoHome')?.addEventListener('click',()=>{folder='home';lessonId=projectId=null;draw()});$('osRepoBack')?.addEventListener('click',()=>{lessonId=null;folder='foundations';draw()});$('osProjectBack')?.addEventListener('click',()=>{projectId=null;folder='projects';draw()});
 $('osRepoSearch')?.addEventListener('input',e=>{if(folder==='home'){folder='foundations';const q=e.target.value;draw();$('osRepoSearch').value=q;$('osRepoSearch').focus();$('osRepoSearch').dispatchEvent(new Event('input'));return;}let count=0;for(const b of dialog.querySelectorAll('[data-search]')){b.hidden=!b.dataset.search.includes(e.target.value.toLowerCase());if(!b.hidden)count++;}$('osSearchEmpty').hidden=count>0;});
 const current=()=>lessons.find(l=>l.id===lessonId);for(const b of dialog.querySelectorAll('[data-quiz]'))b.onclick=()=>{const l=current(),right=Number(b.dataset.quiz)===l.quiz[2];quizFeedback=right?l.quiz[3]:'Try again. Read the explanation above and compare each choice.';if(right&&!progress().quizzes.includes(l.id))progress().quizzes.push(l.id);const scroll=dialog.querySelector('.os-app-body').scrollTop;draw();dialog.querySelector('.os-app-body').scrollTop=scroll;};
 $('osPreviousLesson')?.addEventListener('click',()=>{lessonId=lessons[lessons.indexOf(current())-1].id;quizFeedback='';draw()});$('osNextLesson')?.addEventListener('click',()=>{lessonId=lessons[lessons.indexOf(current())+1].id;quizFeedback='';draw()});$('osTryCommand')?.addEventListener('click',()=>{const command=current().commands[ubuntu()?'ubuntu':'windows'];if(!ubuntu())shell=/^(ipconfig|netstat|tracert|nslookup)/i.test(command)?'cmd':'powershell';openApp('terminal');$('osCommand').value=command;});
 $('osSubnetForm')?.addEventListener('submit',e=>{e.preventDefault();calculateSubnet()});if($('osSubnetResult'))calculateSubnet();
 $('osProjectApp')?.addEventListener('click',()=>{const p=projects.find(x=>x.id===projectId);openApp(p.id==='cloud'?'cloud':p.app)});$('osCheckProject')?.addEventListener('click',()=>{const p=projects.find(x=>x.id===projectId);notice=checkProject(p)?'✓ Project passed. The lab detected the required evidence.':'Not complete yet. Follow the task, check power and network settings, then try again.';draw()});
 $('osCreateVm')?.addEventListener('submit',e=>{e.preventDefault();const r=E.createVM(state(),$('osVmHost').value,$('osVmName').value,Number($('osVmRam').value),Number($('osVmCpu').value),Number($('osVmDisk').value),'external');notice=r.message;api.render?.();draw()});
 for(const b of dialog.querySelectorAll('[data-guest-install]'))b.onclick=()=>guestAction(b.dataset.guestInstall,'install');for(const b of dialog.querySelectorAll('[data-guest-run]'))b.onclick=()=>{const v=state().vms.find(v=>v.id===b.dataset.guestRun);guestAction(v.id,v.running?'stop':'start')};for(const b of dialog.querySelectorAll('[data-guest-open]'))b.onclick=()=>open(b.dataset.guestOpen);for(const b of dialog.querySelectorAll('[data-guest-switch]'))b.onchange=()=>{state().vms.find(v=>v.id===b.dataset.guestSwitch).mode=b.value;api.render?.();draw()};
 $('osCloudForm')?.addEventListener('submit',e=>{e.preventDefault();Object.assign(state().cloud,{model:$('osCloudModel').value,service:$('osCloudService').value,account:true});notice='Learning account provisioned. No real subscription was created.';api.render?.();draw()});$('osBackup')?.addEventListener('click',()=>{const source=E.find(state(),$('osBackupSource').value);if(!source){notice='Prepare a server or NAS first.';draw();return;}const r=E.test(state(),source.id,'cloud','https');if(r.ok)Object.assign(state().cloud,{backup:true,verified:false,sourceName:source.name,capacity:E.raidStatus(source).usable});notice=r.ok?'Simulated recovery record saved. Verify it next.':r.why;api.render?.();draw()});$('osVerifyBackup')?.addEventListener('click',()=>{if(state().cloud.backup)state().cloud.verified=true;notice='Recovery record verified. A real backup plan also tests file restoration.';api.render?.();draw()});
 }
 function execute(raw){const command=raw.trim(),r=runCommand(state(),machine,command,shell);if(r.clear)log=[];else{log.push({prompt:shellName(),command,output:r.output,ok:r.ok});log=log.slice(-60);}if(command){history.push(command);history=history.slice(-60);}historyIndex=history.length;recordCommand(command,r);if(r.changed)api.render?.();draw();$('osCommand')?.focus();const term=dialog.querySelector('.os-app-body');if(term)term.scrollTop=term.scrollHeight;}
 function guestAction(id,action){const r=E.vmAction(state(),id,action);notice=r.message;api.render?.();draw();}
 function calculateSubnet(){const r=subnet($('osSubnetIp').value.trim(),$('osPrefix').value);$('osSubnetResult').innerHTML=r?`<div class="os-bits" aria-label="${r.prefix} network bits followed by ${32-r.prefix} host bits">${Array.from({length:32},(_,i)=>`<span class="${i<r.prefix?'net':'host'}">${i<r.prefix?'1':'0'}</span>`).join('')}</div><p><b>Blue = network bits. Amber = host bits.</b></p><dl class="os-properties"><dt>Mask</dt><dd>${r.mask}</dd><dt>Network</dt><dd>${r.network}/${r.prefix}</dd><dt>Broadcast</dt><dd>${r.broadcast}</dd><dt>Host range</dt><dd>${r.first} → ${r.last}</dd><dt>Address count</dt><dd>${r.addresses.toLocaleString()} total · ${r.hosts.toLocaleString()} host addresses</dd></dl><p>${esc(r.note)}</p>`:'<p>Use a valid four-octet IPv4 address and a prefix from 0 to 32.</p>';}
 function bindDrag(){const bar=dialog.querySelector('.os-titlebar'),win=dialog.querySelector('.os-window');if(!bar||maximized)return;bar.onpointerdown=e=>{if(e.target.closest('button')||e.button!==0)return;const start={x:e.clientX,y:e.clientY,dx:windowPosition?.x||0,dy:windowPosition?.y||0},area=dialog.querySelector('.os-workspace').getBoundingClientRect(),rect=win.getBoundingClientRect();bar.setPointerCapture(e.pointerId);bar.onpointermove=ev=>{const dx=Math.max(area.left+8-rect.left,Math.min(area.right-8-rect.right,ev.clientX-start.x)),dy=Math.max(area.top+36-rect.top,Math.min(area.bottom-70-rect.bottom,ev.clientY-start.y));windowPosition={x:start.dx+dx,y:start.dy+dy};win.style.setProperty('--os-dx',windowPosition.x+'px');win.style.setProperty('--os-dy',windowPosition.y+'px');};bar.onpointerup=bar.onpointercancel=()=>{bar.onpointermove=null;};};}
 dialog.addEventListener('cancel',()=>{api.render?.();lastFocus?.focus?.()});
 function refresh(){if(!dialog.open)return;if(owner!==state()){close();owner=state();return;}if(!ctx().status?.ok)draw();}
 return {open,close,refresh};
}
