// Browser navigation is simulated. Never fetch or embed a user-entered address.
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const isBrowser=app=>app==='browser'||app==='firefox';
export const createBrowserState=()=>({url:'https://example.com',result:null,history:[],index:-1});
function normalize(raw){const value=String(raw).trim().slice(0,2048);if(!value||/^about:(newtab|home)$/i.test(value))return 'about:newtab';if(/^example\.com\/?$/i.test(value))return 'https://example.com';return value;}
function resolvePage(url,resolve){if(url==='about:newtab')return null;if(/^https:\/\/example\.com\/?$/i.test(url))return resolve();return {ok:false,why:'This practice browser supports https://example.com. Other addresses and search engines are not modeled; this message does not mean your network is broken.',unsupported:true};}
export function visitBrowser(s,raw,resolve,replace=false){const url=normalize(raw);s.url=url;s.result=resolvePage(url,resolve);if(replace&&s.index>=0)s.history[s.index]=url;else{s.history=s.history.slice(0,s.index+1);s.history.push(url);if(s.history.length>50)s.history.shift();s.index=s.history.length-1;}return s.result;}
export function moveBrowser(s,delta,resolve){const index=s.index+delta;if(index<0||index>=s.history.length)return null;s.index=index;s.url=s.history[index];s.result=resolvePage(s.url,resolve);return s.result;}
export function browserMarkup(app,s,icon){const fox=app==='firefox',name=fox?'Firefox':'Chrome',r=s.result,home=!r,title=home?'New Tab':r.ok?'Example Domain':'Page unavailable';return `<div class="practice-browser browser-${fox?'firefox':'chrome'}"><div class="browser-tabstrip"><div class="browser-tab">${icon(app)}<span>${title}</span></div><span class="browser-simulation-label">Practice browser</span></div><form id="osBrowserForm" class="browser-navigation"><div class="browser-nav-actions"><button type="button" id="osBrowserBack" aria-label="Back in ${name}" title="Back" ${s.index>0?'':'disabled'}>←</button><button type="button" id="osBrowserForward" aria-label="Forward in ${name}" title="Forward" ${s.index<s.history.length-1?'':'disabled'}>→</button><button type="button" id="osBrowserReload" aria-label="Reload page" title="Reload · check the current network">↻</button><button type="button" id="osBrowserHome" aria-label="Browser home" title="Home">${icon('home')}</button></div><label for="osUrl" class="os-sr-only">Website address</label><input id="osUrl" aria-label="Website address" value="${esc(s.url==='about:newtab'?'':s.url)}" placeholder="Enter https://example.com" autocomplete="off" autocapitalize="off" spellcheck="false" maxlength="2048"><button class="browser-go" type="submit">Go</button></form>${home?`<section class="browser-home">${icon(app)}<h2>${name}</h2><p>Open a page through your lab’s network.</p><button id="osBrowserExample">${icon('network')}<span><b>Example Domain</b><small>https://example.com</small></span><span>→</span></button><p class="browser-home-hint">Try it: open the page, change a network setting, then reload.</p></section>`:`<section class="os-browser-result browser-page ${r.ok?'pass':'fail'}" aria-live="polite"><span class="browser-result-symbol">${r.ok?'✓':'!'}</span><h2>${r.ok?'Example Domain':r.unsupported?'Address outside this lab':'This page could not load'}</h2>${r.ok?'<p class="browser-success-label">Example page received</p>':''}<p>${esc(r.why)}</p>${r.trace?.length?`<details class="browser-path"><summary>See the request’s path</summary><ol>${r.trace.map(t=>`<li>${esc(t)}</li>`).join('')}</ol></details>`:''}${!r.ok?`<div class="browser-repair">${r.unsupported?'<button id="osBrowserExample">Open the practice page</button>':'<button data-osapp="settings">Open network settings</button><button data-osapp="terminal">Open Terminal</button>'}</div>`:''}</section>`}<footer class="browser-lab-note">Modeled pages only · Reload checks current lab connections, routing, DNS and HTTPS. No external web browsing.</footer></div>`;}
