// Interaction layer: pointer movement never rebuilds the scene during a drag.
export function clampPoint(x,y){return [Math.max(13,Math.min(87,x)),Math.max(25,Math.min(89,y))];}
export function setupLabUX(api){
 const $=id=>document.getElementById(id),scene=$('scene');let drag=null,raf=0,suppressUntil=0,activeSection='Ports & cables',inspected=null,utterance=null,voiceToken=0,spokenStep='',voiceState='idle',voices=[];
 const state=()=>api.getState(),supported=!!window.speechSynthesis&&typeof window.SpeechSynthesisUtterance==='function';
 // Put the compact lesson above the entire lab, keeping the bench near the top.
 const workspace=document.querySelector('.workspace');workspace.before($('coach'));$('goalPrev').textContent='← Back';$('goalPrev').setAttribute('aria-label','Previous lesson prompt');
 const toolbar=document.createElement('div');toolbar.className='bench-toolbar';toolbar.innerHTML='<div><strong>Hands-on workbench</strong><span>Drag to move · click to inspect · connect labeled ports</span></div><button id="tidyBench">Arrange view</button><button id="benchFocus" aria-pressed="false">Expand bench</button>';document.querySelector('.lab-surface').prepend(toolbar);
 const mobilebar=document.createElement('nav');mobilebar.className='lab-jumps';mobilebar.setAttribute('aria-label','Lab shortcuts');mobilebar.innerHTML='<a href="#coach">Lesson</a><a href="#inventory">Equipment</a><a href="#scene">Workbench</a><a href="#devicePanel">Settings</a><a href="#testResult">Test results</a>';workspace.before(mobilebar);
 const close=document.createElement('button');close.id='closeInspector';close.textContent='Back to bench';document.querySelector('.inspector .section-heading').append(close);close.onclick=()=>{document.querySelector('.inspector').classList.remove('mobile-open');scene.scrollIntoView({block:'center',behavior:'smooth'})};
 const shelf=document.querySelector('.shelf');shelf.querySelector('.small').textContent='Drag a handle onto the bench, or click an item to add it. Then click the placed equipment to inspect it.';
 for(const b of $('inventory').querySelectorAll('button')){const handle=document.createElement('span');handle.className='grab-handle';handle.textContent='⠿';handle.title='Drag this equipment to the workbench';handle.setAttribute('aria-hidden','true');b.prepend(handle);b.title='Drag to place, or click to add';}
 const toolHeading=shelf.querySelectorAll('h2')[1];const tools=document.createElement('details');tools.className='shelf-group';tools.open=!window.matchMedia?.('(max-width:780px)')?.matches;tools.innerHTML='<summary>Safety & power tools</summary>';toolHeading.before(tools);tools.append($('safetyTools'),$('powerOutage'));toolHeading.remove();const saves=document.createElement('details');saves.className='shelf-group';saves.innerHTML='<summary>Save, load & reset</summary>';shelf.append(saves);for(const id of ['saveLab','loadLab','saveStatus','exportLab'])saves.append($(id));saves.append(shelf.querySelector('.file-button'),$('resetOpen'));
 $('coach').querySelector('details').id='lessonDetails';const audio=document.createElement('details');audio.id='audioOptions';audio.className='audio-options';audio.innerHTML='<summary>Voice & listening options</summary><div class="voice-options"><label>Voice<select id="narratorVoice"><option value="">Device default voice</option></select></label><label>Speed<select id="narratorRate"><option value="0.75">0.75× · slower</option><option value="0.9" selected>0.9× · clear</option><option value="1">1× · normal</option><option value="1.15">1.15× · faster</option></select></label><label class="check"><input type="checkbox" id="autoNarrate"> Read each next lesson automatically</label><label class="check"><input type="checkbox" id="readDetails" checked> Include the exact steps</label></div><p class="small">Uses the voices available in your browser. Press Play to begin. The written lesson is always available.</p>'; $('coach').append(audio);
 const pause=document.createElement('button');pause.id='pauseVoice';pause.textContent='Pause';pause.disabled=true;$('coachVoice').after(pause);$('coachVoice').textContent='▶ Play lesson';const status=document.createElement('span');status.id='voiceStatus';status.setAttribute('role','status');status.textContent=supported?'Narration ready':'Narration unavailable in this browser';$('coach').querySelector('.coach-top').append(status);
 const readDevice=document.createElement('button');readDevice.id='readDevice';readDevice.textContent='▶ Explain selected device';document.querySelector('.inspector .section-heading').after(readDevice);
 const readTest=document.createElement('button');readTest.id='readTest';readTest.textContent='▶ Read test result';document.querySelector('.test-bench .section-heading').append(readTest);
 function setVoiceStatus(text,mode='idle'){voiceState=mode;status.textContent=text;pause.disabled=mode==='idle';pause.textContent=mode==='paused'?'Resume':'Pause';$('coachVoice').textContent=mode==='playing'?'↻ Replay lesson':'▶ Play lesson';}
 function stop(){voiceToken++;window.speechSynthesis?.cancel();utterance=null;setVoiceStatus(supported?'Narration stopped':'Narration unavailable in this browser');}
 function speak(text,label='Lesson'){if(!supported)return api.toast('Narration is unavailable here. The complete text remains on screen.',false);stop();const token=voiceToken,parts=text.split(/(?<=[.!?])\s+/).filter(Boolean);let index=0;setVoiceStatus('Reading '+label.toLowerCase(),'playing');
  const next=()=>{if(token!==voiceToken)return;if(index>=parts.length){utterance=null;setVoiceStatus(label+' finished');return;}utterance=new window.SpeechSynthesisUtterance(parts[index++].trim());utterance.rate=Number($('narratorRate').value);const selected=voices.find(v=>v.voiceURI===$('narratorVoice').value);if(selected)utterance.voice=selected;utterance.onend=next;utterance.onerror=e=>{if(token!==voiceToken||e.error==='canceled'||e.error==='interrupted')return;setVoiceStatus('Voice could not play. Try another voice.');};window.speechSynthesis.speak(utterance);};next();}
 function readLesson(){const text=$('goalTitle').textContent+'. '+$('goalBody').textContent+($('readDetails').checked?' '+$('goalHelp').textContent:'');speak(text,'Lesson');}
 function fillVoices(){if(!supported)return;const current=$('narratorVoice').value;voices=window.speechSynthesis.getVoices();$('narratorVoice').replaceChildren(new Option('Device default voice',''));for(const v of voices.filter(v=>/^en/i.test(v.lang)))$('narratorVoice').add(new Option(v.name+' · '+v.lang,v.voiceURI));if([...$('narratorVoice').options].some(o=>o.value===current))$('narratorVoice').value=current;}
 fillVoices();window.speechSynthesis?.addEventListener('voiceschanged',fillVoices);
 $('coachVoice').onclick=readLesson;$('stopVoice').onclick=stop;pause.onclick=()=>{if(voiceState==='paused'){window.speechSynthesis.resume();setVoiceStatus('Narration resumed','playing')}else if(voiceState==='playing'){window.speechSynthesis.pause();setVoiceStatus('Narration paused','paused')}};
 $('readDevice').onclick=()=>{if(!state().selected)return api.toast('Select equipment on the bench first.',false);speak($('deviceTitle').textContent+'. '+$('deviceIntro').textContent,'Device explanation')};$('readTest').onclick=()=>speak($('testResult').textContent,'Test result');for(const id of ['narratorRate','narratorVoice'])$(id).onchange=()=>{if(voiceState!=='idle')stop()};
 if(!supported)for(const id of ['coachVoice','pauseVoice','stopVoice','readDevice','readTest','autoNarrate','narratorVoice','narratorRate'])$(id).disabled=true;
 // Auto narration follows user navigation, never configuration re-renders.
 function onLesson(){const k=state().mission+':'+state().step;if(k!==spokenStep){const hadStep=spokenStep!=='';spokenStep=k;if(hadStep){stop();if($('autoNarrate').checked)readLesson();}}}
 function organizeInspector(){const panel=$('devicePanel');if(!panel.firstChild)return;const id=state().selected;if(inspected!==id){activeSection='Ports & cables';inspected=id;document.querySelector('.inspector').scrollTop=0;}let group=null;for(const child of [...panel.children]){if(child.tagName==='H3'){const title=child.textContent;group=document.createElement('details');group.className='inspector-group';group.open=title===activeSection;const sum=document.createElement('summary');sum.textContent=title;group.append(sum);child.before(group);child.remove();const section=group;section.addEventListener('toggle',()=>{if(section.open)activeSection=title});}else if(child.tagName==='HR'||child.id==='removeDevice'){group=null;}else if(group)group.append(child);}
 const power=$('togglePower');if(power)power.classList.add('power-button');
 }
 function drawWires(overrides={}){const map={...api.positions(),...overrides},height=parseFloat(scene.style.height)||640;for(const p of $('wires').querySelectorAll('path[data-link]')){const l=state().links.find(l=>l.id===p.dataset.link);if(!l)continue;const a=map[l.a],b=map[l.b];if(!a||!b)continue;p.setAttribute('d',`M${a[0]*10},${a[1]*height/100} C${a[0]*10},${(a[1]+12)*height/100} ${b[0]*10},${(b[1]+12)*height/100} ${b[0]*10},${b[1]*height/100}`);}}
 function savePosition(id,point){const s=state();s.layout??={};s.layout[s.view]??={};s.layout[s.view][id]=point;}
 function refreshDrag(){raf=0;if(!drag?.moving)return;const r=scene.getBoundingClientRect(),x=(drag.cx-r.left)/r.width*100,y=(drag.cy-r.top)/r.height*100;drag.inside=drag.cx>=r.left&&drag.cx<=r.right&&drag.cy>=r.top&&drag.cy<=r.bottom;drag.point=clampPoint(x-drag.offsetX,y-drag.offsetY);scene.classList.toggle('drop-ready',drag.inside);if(drag.ghost){drag.ghost.style.transform=`translate3d(${drag.cx-56}px,${drag.cy-55}px,0)`;}else if(drag.node){drag.node.style.left=drag.point[0]+'%';drag.node.style.top=drag.point[1]+'%';drawWires({[drag.id]:drag.point});}}
 function cleanup(){if(raf)cancelAnimationFrame(raf);raf=0;drag?.ghost?.remove();drag?.node?.classList.remove('dragging');scene.classList.remove('drop-ready');document.body.classList.remove('lab-dragging');drag=null;}
 function cancel(){if(!drag)return;const moved=drag.moving;cleanup();if(moved){suppressUntil=Date.now()+350;api.renderScene();api.toast('Placement canceled. Equipment stays where it was.')}}
 document.addEventListener('pointerdown',e=>{if(e.button!==0||drag)return;const node=e.target.closest('[data-add],[data-device]');if(!node)return;if(e.pointerType==='touch'&&node.dataset.add&&!e.target.closest('.grab-handle'))return;const id=node.dataset.device,d=id?state().devices.find(d=>d.id===id):null;if(d&&['wall','isp'].includes(d.type))return;if(!['bench','rear','network'].includes(state().view)){return;}const rect=scene.getBoundingClientRect(),p=id?api.positions()[id]:null;drag={node,id,type:node.dataset.add,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,cx:e.clientX,cy:e.clientY,moving:false,offsetX:p?(e.clientX-rect.left)/rect.width*100-p[0]:0,offsetY:p?(e.clientY-rect.top)/rect.height*100-p[1]:0};node.setPointerCapture?.(e.pointerId);});
 document.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;drag.cx=e.clientX;drag.cy=e.clientY;if(!drag.moving&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>6){drag.moving=true;document.body.classList.add('lab-dragging');if(drag.type){const ghost=drag.node.cloneNode(true);ghost.removeAttribute('id');ghost.removeAttribute('data-add');ghost.className='drag-ghost';ghost.setAttribute('aria-hidden','true');document.body.append(ghost);drag.ghost=ghost;}else drag.node.classList.add('dragging');}if(drag.moving){e.preventDefault();if(!raf)raf=requestAnimationFrame(refreshDrag);}}, {passive:false});
 document.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointerId)return;if(!drag.moving){cleanup();return;}drag.cx=e.clientX;drag.cy=e.clientY;refreshDrag();const {inside,point,type,id}=drag;suppressUntil=Date.now()+450;cleanup();if(!inside){api.renderScene();api.toast('Drop inside the workbench. Nothing was moved.',false);return;}if(type){const r=api.addDevice(type);if(!r.ok){api.result(r);return;}state().selected=r.id;savePosition(r.id,point);api.result({...r,message:'Placed on the bench. Select its picture to connect power and data.'});}else{savePosition(id,point);state().selected=id;api.renderScene();api.renderInspector();api.toast('Position saved. Cables stay connected.');} });
 document.addEventListener('pointercancel',cancel);window.addEventListener('blur',cancel);document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancel();document.querySelector('.inspector').classList.remove('mobile-open');}const node=e.target.closest?.('[data-device]');if(!node||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||!['bench','rear','network'].includes(state().view))return;const d=state().devices.find(d=>d.id===node.dataset.device);if(!d||['wall','isp'].includes(d.type))return;e.preventDefault();const p=api.positions()[d.id],step=e.shiftKey?5:1;savePosition(d.id,clampPoint(p[0]+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),p[1]+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0)));api.renderScene();document.querySelector(`[data-device="${d.id}"]`)?.focus();});
 document.addEventListener('click',e=>{if(Date.now()<suppressUntil&&e.target.closest('[data-add],[data-device]')){e.preventDefault();e.stopImmediatePropagation();}},true);
 document.addEventListener('dragstart',e=>{if(e.target.closest('[data-device],[data-add]'))e.preventDefault()});
 $('tidyBench').onclick=()=>{if(state().layout)delete state().layout[state().view];api.renderScene();api.toast('This view is arranged. Saved connections are unchanged.')};$('benchFocus').onclick=()=>{const active=workspace.classList.toggle('bench-expanded');$('benchFocus').setAttribute('aria-pressed',active);$('benchFocus').textContent=active?'Show equipment & settings':'Expand bench'};
 function revealInspector(){workspace.classList.remove('bench-expanded');$('benchFocus').setAttribute('aria-pressed','false');$('benchFocus').textContent='Expand bench';if(window.matchMedia?.('(max-width:1100px)')?.matches)document.querySelector('.inspector').classList.add('mobile-open');}
 $('scene').addEventListener('click',e=>{if(Date.now()>=suppressUntil&&e.target.closest('[data-device]'))revealInspector()});document.querySelector('a[href="#devicePanel"]').onclick=e=>{e.preventDefault();revealInspector();};
 window.addEventListener('pagehide',stop);organizeInspector();onLesson();return {organizeInspector,onLesson,stop,revealInspector};
}
