import assert from 'node:assert/strict';import fs from 'node:fs';import * as E from './lab-engine.js';
let checks=0;const yes=(x,m)=>{assert.ok(x,m);checks++},no=(x,m)=>yes(!x,m);const s=E.fresh();const add=t=>E.find(s,E.addDevice(s,t).id);const wire=(a,ap,b,bp,t='cat5e',len=6)=>{const r=E.connect(s,a.id,ap,b.id,bp,t,len);yes(r.ok,r.message);return s.links.at(-1)};
const wall=E.find(s,'wall'),isp=E.find(s,'isp'),p=add('pdu'),o=add('ont'),r=add('router'),sw=add('switch'),l=add('laptop');
wire(wall,'out1',p,'ac','power');[o,r,sw,l].forEach((d,i)=>wire(p,'out'+(i+1),d,'ac','power'));s.devices.forEach(d=>d.on=true);wire(isp,'fiber',o,'fiber','sc');wire(o,'lan',r,'wan');wire(r,'lan1',sw,'p1');const last=wire(l,'eth',sw,'p2');no(E.test(s,l.id).ok,'DHCP off blocks lease');r.router.dhcp=true;yes(E.test(s,l.id).ok,'working network');last.broken=true;no(E.test(s,l.id).ok,'damaged link');last.broken=false;r.router.dns='192.168.50.250';no(E.test(s,l.id).ok,'DNS failure');yes(E.test(s,l.id,'internet','ping').ok,'ICMP by IP independent of DNS');r.router.dns=r.router.lan;no(E.test(s,l.id,'internet','smb').ok,'no Internet SMB');r.router.nat=false;no(E.test(s,l.id).ok,'NAT needed');r.router.nat=true;no(E.connect(s,l.id,'eth',r.id,'lan2','cat5e',6).ok,'occupied port');no(E.connect(s,r.id,'lan2',sw.id,'p3','cat5e',6).ok,'bridge loop');no(E.connect(s,r.id,'lan2',sw.id,'p3','cat5e',329).ok,'length');
const h=add('server');no(E.fitPart(s,h.id,'cpu','AM4-8').ok,'ESD required');s.safety={mat:true,strap:true,clearance:true};no(E.fitPart(s,h.id,'cpu','LGA').ok,'socket mismatch');no(E.fitPart(s,h.id,'ram','DDR5').ok,'RAM mismatch');for(const [part,value]of [['cpu','AM4-8'],['ram','32'],['cooler','yes'],['nic','1g'],...Array.from({length:4},()=>['disk','1'])])yes(E.fitPart(s,h.id,part,value).ok,'fit '+part);h.rails=true;yes(E.mount(s,h.id,4).ok);const u=add('ups');u.rails=true;no(E.mount(s,u.id,4).ok,'rack overlap');yes(E.mount(s,u.id,1).ok);s.links=s.links.filter(x=>x.type!=='power'||x.b!==p.id);wire(wall,'out1',u,'ac','power');wire(u,'out1',p,'ac','power');wire(p,'out5',h,'ac','power');u.on=h.on=true;no(E.fitPart(s,h.id,'ram','64').ok,'live parts blocked');yes(E.configureRaid(s,h.id,'10').ok);yes(E.raidStatus(h).usable===2);h.os='Hypervisor';h.drivers=h.virt=true;wire(h,'eth',sw,'p3');yes(E.test(s,h.id).ok,'server online');yes(E.createVM(s,h.id,'Web-Lab',4,2,40,'external').ok);const v=s.vms[0];v.os='Linux';v.running=v.service=true;yes(E.testVM(s,l.id,v.id).ok,'external guest');v.mode='private';no(E.testVM(s,l.id,v.id).ok,'private isolation');v.mode='internal';no(E.testVM(s,l.id,v.id).ok,'internal isolation');v.mode='external';no(E.createVM(s,h.id,'Too large',32,4,40,'external').ok,'RAM bound');no(E.createVM(s,h.id,'Bad',NaN,2,40,'external').ok,'NaN blocked');h.disks[0].failed=true;yes(E.testVM(s,l.id,v.id).ok,'one failed mirror member');h.disks[2].failed=true;yes(E.testVM(s,l.id,v.id).ok,'one member per pair');h.disks[1].failed=true;no(E.testVM(s,l.id,v.id).ok,'lost mirror pair');h.disks.forEach(x=>x.failed=false);s.outage=true;yes(E.powered(s,u.id),'UPS battery');yes(E.test(s,l.id).ok,'UPS backed path');u.on=false;no(E.test(s,l.id).ok,'UPS off');u.on=true;s.outage=false;
const ap=add('ap');wire(ap,'eth',sw,'p4');ap.on=true;l.network.wifi=true;l.network.ssid='HomeLab';l.network.password='wrong';no(E.network(s,l.id).ok,'wrong Wi-Fi secret');l.network.password='learnlab123';yes(E.test(s,l.id).ok,'wireless');sw.poe=false;no(E.test(s,l.id).ok,'PoE loss');sw.poe=true;l.network.wifi=false;s.links=s.links.filter(x=>x.a!==ap.id&&x.b!==ap.id);
const l2=add('laptop');wire(p,'out6',l2,'ac','power');l2.on=true;r.router.secondary=true;sw.ports.p4.vlan=20;sw.ports.p5.vlan=20;wire(l2,'eth',sw,'p4');wire(r,'lan2',sw,'p5');yes(E.network(s,l2.id).ip.startsWith('192.168.60.'),'second DHCP subnet');yes(E.test(s,l.id,l2.id,'ping').ok,'routing');r.router.routing=false;no(E.test(s,l.id,l2.id,'ping').ok,'routing disabled');r.router.routing=true;l2.network={...l2.network,mode:'static',ip:'192.168.60.100',mask:'255.255.255.0',gateway:'192.168.60.99',dns:'1.1.1.1'};no(E.test(s,l.id,l2.id,'ping').ok,'wrong return gateway');l2.network.gateway='192.168.60.1';yes(E.test(s,l.id,l2.id,'ping').ok);
const n=add('nas');for(let i=0;i<4;i++)yes(E.fitPart(s,n.id,'disk','1').ok);wire(p,'out7',n,'ac','power');n.on=true;yes(E.configureRaid(s,n.id,'5').ok);wire(n,'eth',sw,'p6');n.services.file=true;yes(E.test(s,l.id,n.id,'smb').ok,'NAS SMB');n.disks[0].failed=true;yes(E.test(s,l.id,n.id,'smb').ok,'RAID5 degraded');n.disks[1].failed=true;no(E.test(s,l.id,n.id,'smb').ok,'RAID5 tolerance');n.disks.forEach(x=>x.failed=false);yes(E.configureRaid(s,n.id,'6').ok);n.disks[0].failed=n.disks[1].failed=true;yes(E.test(s,l.id,n.id,'smb').ok,'RAID6 tolerates two');n.disks[2].failed=true;no(E.test(s,l.id,n.id,'smb').ok,'RAID6 third failure');n.disks.forEach(x=>x.failed=false);
s.cloud={model:'hybrid',service:'iaas',account:true};yes(E.test(s,h.id,'cloud').ok,'cloud path');s.cloud.account=false;no(E.test(s,h.id,'cloud').ok,'cloud unprovisioned');
for(const level of ['0','1','5','6','10']){const count=level==='1'?2:4,d={raid:level,disks:Array.from({length:count},()=>({tb:2,failed:false}))};yes(E.raidStatus(d).ok,'RAID '+level);d.disks[0].failed=true;yes(E.raidStatus(d).ok===(level!=='0'),'first failure '+level)}
fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync('test-results/home-lab-demo.json',JSON.stringify(s,null,2));console.log(`${checks} home lab engine assertions passed.`);
