import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {parseHTML} from 'linkedom';import * as E from './lab-engine.js';
const {document,HTMLSelectElement,HTMLElement,Event}=parseHTML(fs.readFileSync('home-lab.html','utf8'));
Object.defineProperty(HTMLSelectElement.prototype,'value',{get(){const opts=[...this.querySelectorAll('option')],o=opts.find(o=>o.hasAttribute('selected'))||opts[0];return o?.getAttribute('value')??o?.textContent??''},set(v){for(const o of this.querySelectorAll('option')){if((o.getAttribute('value')??o.textContent)===String(v))o.setAttribute('selected','');else o.removeAttribute('selected')}}});Object.defineProperty(HTMLSelectElement.prototype,'options',{get(){return [...this.querySelectorAll('option')]}});HTMLSelectElement.prototype.add=function(x){this.append(x)};HTMLElement.prototype.showModal=function(){this.open=true};HTMLElement.prototype.close=function(){this.open=false};HTMLElement.prototype.scrollIntoView=function(){};HTMLElement.prototype.setPointerCapture=function(){};HTMLElement.prototype.getBoundingClientRect=function(){if(this.classList.contains('shelf'))return {left:0,top:100,width:170,height:640,right:170,bottom:740};if(this.id==='returnZone')return {left:200,top:20,width:1000,height:50,right:1200,bottom:70};return {left:200,top:100,width:1000,height:640,right:1200,bottom:740}};
const spoken=[],store=new Map(),synth={cancel(){},pause(){},resume(){},speak(u){spoken.push(u)},getVoices(){return [{voiceURI:'test',name:'English test',lang:'en-US'}]},addEventListener(){}};class Utterance{constructor(t){this.text=t}};
const win={speechSynthesis:synth,SpeechSynthesisUtterance:Utterance,addEventListener(){},matchMedia:()=>({matches:false})};let tick=null;const ctx=vm.createContext({E,portState:()=>({live:false}),setupHardware:()=>null,document,window:win,Option:function(t,v){const o=document.createElement('option');o.textContent=t;o.value=v;return o;},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},requestAnimationFrame:f=>(tick=f,1),cancelAnimationFrame:()=>tick=null,setTimeout:()=>1,clearTimeout(){},console,Blob,URL});const run=x=>vm.runInContext(x,ctx),$=id=>document.getElementById(id),click=id=>$(id).dispatchEvent(new Event('click',{bubbles:true}));
run(fs.readFileSync('lab-ux.js','utf8').replaceAll('export function','function'));run(fs.readFileSync('lab-app.js','utf8').replace(/^import .*;$/gm,''));
assert.equal(spoken.length,0,'no autoplay');assert.ok($('coach').nextElementSibling.classList.contains('lab-jumps'));click('coachVoice');assert.ok(spoken.length);assert.equal($('voiceStatus').textContent,'Reading lesson');click('pauseVoice');assert.equal($('voiceStatus').textContent,'Narration paused');click('pauseVoice');assert.equal($('voiceStatus').textContent,'Narration resumed');const canceled=spoken.at(-1);click('stopVoice');const count=spoken.length;canceled.onend();assert.equal(spoken.length,count,'canceled chunk cannot restart');assert.equal($('pauseVoice').disabled,true);
run("s.selected=E.addDevice(s,'server').id;render()");assert.equal(document.querySelectorAll('.inspector-group').length,6);assert.equal($('cableType').value,'power','power cord suggested for AC port');const id=run('s.selected');
function pointer(type,target,x,y){const e=new Event(type,{bubbles:true,cancelable:true});Object.assign(e,{button:0,pointerId:1,pointerType:'mouse',clientX:x,clientY:y});target.dispatchEvent(e);if(tick){const f=tick;tick=null;f();}}
const node=document.querySelector(`[data-device="${id}"]`);pointer('pointerdown',node,340,305);pointer('pointermove',node,700,480);pointer('pointerup',node,700,480);const p=run(`s.layout.bench['${id}']`);assert.ok(p[0]>40&&p[1]>45);const exported=run('JSON.stringify(s)');ctx.saved=JSON.parse(exported);assert.equal(run(`validateSave(saved).layout.bench['${id}'][0]`),p[0]);
const moved=document.querySelector(`[data-device="${id}"]`);pointer('pointerdown',moved,700,480);pointer('pointermove',moved,780,550);pointer('pointercancel',moved,780,550);assert.equal(run(`s.layout.bench['${id}'][0]`),p[0],'cancel restores position');
const shelf=document.querySelector('[data-add="laptop"]');const before=run('s.devices.length');pointer('pointerdown',shelf,80,300);pointer('pointermove',shelf,820,510);pointer('pointerup',shelf,820,510);assert.equal(run('s.devices.length'),before+1);assert.ok(run('s.layout.bench[s.selected]'));
pointer('pointerdown',shelf,80,300);pointer('pointermove',shelf,100,50);pointer('pointerup',shelf,100,50);assert.equal(run('s.devices.length'),before+1,'outside drop never adds');click('tidyBench');assert.equal(run('s.layout.bench'),undefined);
const returning=document.querySelector(`[data-device="${id}"]`);pointer('pointerdown',returning,700,480);pointer('pointermove',returning,100,300);pointer('pointerup',returning,100,300);assert.equal(run(`!!E.find(s,'${id}')`),false);assert.equal($('returnNotice').hidden,false);click('undoReturn');assert.equal(run(`!!E.find(s,'${id}')`),true);run(`ux.returnDevice('${id}')`);assert.equal(run(`!!E.find(s,'${id}')`),false);click('undoReturn');assert.equal(run(`!!E.find(s,'${id}')`),true);
$('autoNarrate').checked=true;run('s.step=1;renderCoach();ux.onLesson()');assert.equal($('voiceStatus').textContent,'Reading lesson');click('stopVoice');const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size);
console.log('PASS: real interaction layer, drag placement, outside drops, cancellation, saved coordinates, inspector grouping, sensible cable defaults, opt-in narration, pause/resume/stop and stale speech callbacks.');
