import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {parseHTML} from 'linkedom';import * as E from './lab-engine.js';
const {document,HTMLSelectElement,HTMLElement,Event}=parseHTML(fs.readFileSync('home-lab.html','utf8'));
Object.defineProperty(HTMLSelectElement.prototype,'value',{get(){const opts=[...this.querySelectorAll('option')],o=opts.find(o=>o.hasAttribute('selected'))||opts[0];return o?.getAttribute('value')??o?.textContent??''},set(v){for(const o of this.querySelectorAll('option')){if((o.getAttribute('value')??o.textContent)===String(v))o.setAttribute('selected','');else o.removeAttribute('selected')}}});
HTMLElement.prototype.showModal=function(){this.open=true};HTMLElement.prototype.close=function(){this.open=false};const storage=new Map(),ctx=vm.createContext({E,portState:()=>({live:false}),setupHardware:()=>null,setupLabUX:()=>null,document,window:{},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setTimeout:()=>1,clearTimeout:()=>{},console,Blob,URL});const run=x=>vm.runInContext(x,ctx),$=id=>document.getElementById(id),click=id=>$(id).dispatchEvent(new Event('click',{bubbles:true}));
console.log('UI test source loading');run(fs.readFileSync('lab-app.js','utf8').replace(/^import .*;$/gm,''));console.log('UI initial render');assert.match($('goalTitle').textContent,/Meet the equipment/);assert.equal(document.querySelectorAll('#inventory [data-add]').length,11);
for(const t of Object.keys(E.catalog).filter(t=>!['wall','isp'].includes(t))){run(`s.selected=E.addDevice(s,'${t}').id;render()`);assert.ok($('connectCable'));assert.ok($('devicePanel').textContent.length>100);const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size)}
console.log('All inspectors done');for(const m of ['wired','nas','virtual','wifi','routed','cloud','trouble','free']){run(`start('${m}')`);assert.ok($('goalTitle').textContent.length>3);run('missions[s.mission].steps[s.step].pass()');for(const v of ['bench','rear','rack','network','inside']){run(`s.view='${v}';renderScene()`);assert.match($('scene').className,new RegExp(v))}}
console.log('All missions done');run("start('trouble')");click('runTest');assert.match($('testResult').textContent,/No DHCP offer/);run("s.links.find(x=>x.broken).broken=false;by('router').router.dhcp=true;render()");click('runTest');assert.match($('testResult').textContent,/Name lookup failed/);run("by('router').router.dns='192.168.50.1';render()");click('runTest');assert.match($('testResult').textContent,/PASS/);click('saveLab');run("start('free')");click('loadLab');assert.equal(run('s.mission'),'trouble');assert.equal(run('E.test(s,by("laptop").id).ok'),true);
console.log('Save/load done');ctx.fixture=JSON.parse(fs.readFileSync('test-results/home-lab-demo.json'));run('s=validateSave(fixture);render()');assert.equal(run('s.devices.length'),12);assert.ok($('vmList').textContent.includes('Web-Lab'));run("s.selected=by('server').id;render()");assert.match($('devicePanel').textContent,/RAID/);assert.equal(run('E.testVM(s,by("laptop").id,s.vms[0].id).ok'),true);const data=run('JSON.stringify(s)');ctx.serial=data;run('s=validateSave(JSON.parse(serial));render()');assert.equal(run('s.links.length'),17);
ctx.bad=JSON.parse(data);ctx.bad.vms[0].ram='<img src=x onerror=alert(1)>';assert.throws(()=>run('validateSave(bad)'),/Invalid VM/);ctx.bad=JSON.parse(data);ctx.bad.links.push(ctx.bad.links[0]);assert.throws(()=>run('validateSave(bad)'),/Invalid saved cable/);ctx.bad=JSON.parse(data);ctx.bad.devices.find(d=>d.type==='server').ram='not a number';assert.throws(()=>run('validateSave(bad)'),/Invalid number/);
for(const k of Object.keys(run('definitions'))){run(`showTerm('${k}')`);assert.ok($('termContent').textContent.length>80)}
console.log('PASS: all device inspectors, eight configurations, five views, fault diagnosis, browser save/load, portable round trip, VM rendering, malformed-import rejection, glossary and unique controls.');
run('s=validateSave(fixture);render()');assert.match($('vmHostSummary').textContent,/host is ready/);assert.equal($('createVm').disabled,false);document.querySelector('[data-vmpreset="small"]').dispatchEvent(new Event('click',{bubbles:true}));assert.equal($('vmRam').value,'2');$('vmRam').value=100;$('vmRam').dispatchEvent(new Event('change'));assert.equal($('createVm').disabled,true);assert.match($('vmCreateHint').textContent,/1–32/);document.querySelector('[data-vmpreset="web"]').dispatchEvent(new Event('click',{bubbles:true}));click('createVm');assert.equal(run('s.vms.length'),2);assert.match($('vmFeedback').textContent,/VM created/);assert.equal(document.querySelectorAll('.vm-console').length,2);const mode=document.querySelector('[data-vmmode]');mode.value='private';mode.dispatchEvent(new Event('change',{bubbles:true}));assert.match(document.querySelector('.vm-console').textContent,/host operating system and physical LAN are outside/);run("s.selected=E.addDevice(s,'surge').id;render();s=validateSave(JSON.parse(JSON.stringify(s)));render()");assert.equal(run("E.ofType(s,'surge').length"),1);assert.equal(document.querySelectorAll('.equipment-surge').length,1);console.log('PASS: VM resource preview, presets, create gating, guest cards, switch diagrams, and surge save round trip.');
